### ISSUE TITLE
Devnet ded

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/core#1021]
**Describe the bug**

In case you haven't noticed yet, devnet is currently stuck (for over 24 hours now). In addition, a couple hours ago the [delegate rankings](https://dexplorer.ark.io/delegate-monitor) also disappeared and show 0 for every delegate now. When you do a request to the delegate endpoint (on every node I tested, so not only explorer) it will return rank 0 for all the delegates although their votes are still correct.

Running `SELECT username,vote_balance FROM wallets ORDER BY vote_balance DESC;` shows the correct list of delegates (in the correct order), so seems that db = ok, in memory = ded

**To Reproduce**

1. Go to dexplorer.ark.io
2. Take a look

**Expected behavior**

Not being stuck and delegates showing the correct ranking

**Screenshots**

N/A

**Server (please complete the following information):**

Probably Ubuntu 16.04 for most nodes

**Additional context**

N/A

**Comment by ItsANameToo** [comment]
Some additional info: devnet seems to be fixing itself as we speak, as new blocks are coming in. However, there were 3 transactions on devnet (latest ones) that have now disappeared (had some weird smartbridge message, hence why it stood out).
Another issue is with the [top wallets](https://dexplorer.ark.io/top-wallets/1) as those rankings are also non-existent at the moment.

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/core/commit/248542c9d1ef54dcda3a302460dc9a99ec668363
https://github.com/ArkEcosystem/core/commit/3a39e3b162aa835cf4fc9d4db03eb7482efdd458
