### ISSUE TITLE
core-api V2 transaction search is broken

### ISSUE THREAD

**Issue by j-a-m-l** [ArkEcosystem/core#1036]
Searching by `senderId` is broken on V2

As an example, this payload (using `https://dexplorer.ark.io:8443/api/v2/transactions/search`) returns all the transactions instead of 0:

```json
{"senderId": "D5QtSijK8bwviYuqPPcSiF1Jz73nExDenC"}
```

**Comment by alexbarnsley** [comment]
This what you're looking for?: https://dexplorer.ark.io:8443/api/v2/transactions?senderId=D5QtSijK8bwviYuqPPcSiF1Jz73nExDenC

**Comment by j-a-m-l** [comment]
Yes, that address is empty, but using the endpoint, returns the first page of the txs.

As you have pointed, using `https://dexplorer.ark.io:8443/api/v2/transactions?senderId=D5QtSijK8bwviYuqPPcSiF1Jz73nExDenC` returns the expected result.

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/core/commit/b0fce25be6d1492d0123770b78c0e4818bc070de
