### ISSUE TITLE
Transaction pool sort by fee and limitations

### ISSUE THREAD

**Issue by kristjank** [ArkEcosystem/core#1061]
**Is your feature request related to a problem? Please describe.**
Currently there is no sort of transaction by the dynamic fees. This need to be take into account when getting transaction from the pool.

**Describe the solution you'd like**
Select top 150(blocksize) transaction from the pool, and order them by fee DESC. 
So top transactions get forged.

As this can introduce issues for other transactions types, (vote/unvote order) also enforce a limit on the transaction pool by the sender, in the following form:

TO ALLOW ONLY 1 TRANSACTION OF TYPE VOTE/UNVOTE per SENDER_PUB_KEY in Pool
```
IF incoming transaction  === [VOTE,UNVOTE] THEN:
    IF (sender_public_key already has a VOTE/UNVOTE transaction in POOL) THEN:
        REJECT incoming transaction 
        // allowing the vote transaction to be processed as they are sent    
```

**Further improvements**
After this is working we can think of adding overriding options for specific transactions (similar to ETH or BTC)

**Comment by faustbrian** [comment]
Resolved by https://github.com/ArkEcosystem/core/commit/57317354daf0077a84834d548e419fb775adbea1

**Comment by vasild** [comment]
The second part of this has already been implemented in
https://github.com/ArkEcosystem/core/blob/develop/packages/core-transaction-pool/lib/guard.js#L174
?
