### ISSUE TITLE
Approval percentages are 0 on devnet

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/core#1116]
**Describe the bug**
Approval percentages are always 0, see https://dexplorer.ark.io:8443/api/v2/delegates

Even though some delegates have a very small percentage of votes, at least ArkX should have around 0.38% of approval as that wallet contains 0.38% of the supply.

**To Reproduce**
1. Go to the delegates endpoint https://dexplorer.ark.io:8443/api/v2/delegates
2. Look at the response; all approval properties are 0

**Expected behavior**
Actual approval percentage

**Comment by faustbrian** [comment]
This https://github.com/ArkEcosystem/core/blob/develop/packages/crypto/lib/utils/bignum.js#L3 causes this https://github.com/ArkEcosystem/core/blob/develop/packages/core-utils/lib/delegate-calculator.js#L22 calculation to result in 0 as `delegate.voteBalance.times(100).dividedBy(totalSupply)` has no decimals.

**Comment by faustbrian** [comment]
Could do something like this just for that specific utility.

```
'use strict'

const container = require('@arkecosystem/core-container')
const BigNumber = require('bignumber.js')
BigNumber.config({DECIMAL_PLACES: 2})

/**
 * Calculate the approval for the given delegate.
 * @param  {Delegate} delegate
 * @param  {Number} height
 * @return {Number} Approval, with 2 decimals
 */
exports.calculateApproval = (delegate, height) => {
  const config = container.resolvePlugin('config')

  if (!height) {
    height = container.resolvePlugin('blockchain').getLastBlock().data.height
  }

  const constants = config.getConstants(height)
  const totalSupply = new BigNumber(config.genesisBlock.totalAmount).plus((height - constants.height) * constants.reward)

  return +delegate.voteBalance.times(100).dividedBy(totalSupply).toFixed(2)
}

/**
 * Calculate the productivity of the given delegate.
 * @param  {Delegate} delegate
 * @return {Number} Productivity, with 2 decimals
 */
exports.calculateProductivity = delegate => {
  const missedBlocks = +delegate.missedBlocks
  const producedBlocks = +delegate.producedBlocks

  if (!missedBlocks && !producedBlocks) {
    return +(0).toFixed(2)
  }

  return +(100 - (missedBlocks / ((producedBlocks + missedBlocks) / 100))).toFixed(2)
}
```
