### ISSUE TITLE
Make currently used logfile name fixed

### ISSUE THREAD

**Issue by geops22** [ArkEcosystem/core#1125]
**Is your feature request related to a problem? Please describe.**
The new core has the currently used logfile name datestamped. This will pose issues with any monitoring scripts that examine the logfile as its name will change every day.

**Describe the solution you'd like**
I propose keeping the logfile name in use fixed, e.g. ark.log and once archived add a datestamp to the archive name as that will not longer be actively examined.

**Comment by paroxysm** [comment]
It appears this is something we can do with our logging framework, https://github.com/winstonjs/winston-daily-rotate-file
If we take out `%DATE%` fragment from the `filename` property on our winston defaults and keep `datePattern`, we should be able to achieve this.

**Comment by geops22** [comment]
The code changes moved the datestamp to the end of the file but didn't eliminate it.
