### ISSUE TITLE
endpoint GET /peer/blocks is a lot slower than v1

### ISSUE THREAD

**Issue by fix** [ArkEcosystem/core#1151]
**Describe the bug**
when nodes rebuilds rfom network they ping /peer/blocks to get blocks in a range.
on v2 this is slow because contrary to v1 it needs to join programatically 'blocks' and 'transactions' table

Possible solutions:
- find faster way to join
- stream from snapshoted data (since blocks are stored with transactions in the same table)

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/core/pull/2307
