### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by h1psterx** [ArkEcosystem/core#1198]
**Is your feature request related to a problem? Please describe.**

I've seen that the ark-ts has been deprecated and is pointing to this repository. 

Will there be TypeScript support?  PRs accepted?

**Describe the solution you'd like**

Add TypeScript Declaration File (.d.ts).

**Describe alternatives you've considered**

Use the [tsd-jsdoc](https://github.com/englercj/tsd-jsdoc) package to compile the documentation in a valid declaration file.

**Comment by faustbrian** [comment]
There are plans to add TS in the future but things are still under development. Once things are set in stone we will open an issue that will be marked with `help wanted` that can then be worked on.
