### ISSUE TITLE
tiny-secp256k1 try to run python 2.7 but seems my PC run python 3 by default. What you recommend to do?

### ISSUE THREAD

**Issue by officefish** [ArkEcosystem/core#1229]
$ lerna bootstrap
info cli using local version of lerna
lerna notice cli v3.4.3
lerna info versioning independent
lerna info bootstrap root only
yarn install v1.10.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⠐ tiny-secp256k1
error D:\nodejs\lerna-ark\node_modules\tiny-secp256k1: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: D:\nodejs\lerna-ark\node_modules\tiny-secp256k1
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.11.4 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python33\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:275:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:557:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\nodejs\\lerna-ark\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\nodejs\lerna-ark\node_modules\tiny-secp256k1
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in 'root'
lerna ERR! yarn install --mutex network:42424 --non-interactive exited 1 in 'root'

**Comment by supaiku0** [comment]
Currently there are no plans to support Windows. I suggest to use a Linux VM for development or to comply with the error and use Python 2.7. Though it's likely that you will just into more issues down the road that way.

**Comment by officefish** [comment]
Change default python to 2.7 but stil has troubles...  I understand why you not interested in windows suport for node, but I suppose it will be great in future to not use libraries wich use windows build tools and python script for nodejs project. Openpgpjs is good alternative for secp256k1/tiny-secp256k1
Bucause without that your code use msbuild even if you do not support windows.

**Comment by faustbrian** [comment]
If you need windows support you can always send a PR to make it work, that way you help yourself and everyone that works on Windows.

As a tip, it makes more sense to work on a Linux based OS if you work on software that runs on a Linux based OS to minimise the source of things that could cause problems. Keep your development environment as close as possible to the production environment.
