### ISSUE TITLE
core-api: internal server errors on bad orderBy param

### ISSUE THREAD

**Issue by dated** [ArkEcosystem/core#1277]
**Describe the bug**

The core-api doesn't handle bad orderBy params all to well, resulting in internal server errors on several occasions.

- omitting the direction portion
- adding an invalid direction (e.g. `descc`)

For instance
https://dexplorer.ark.io:8443/api/v2/blocks?orderBy=height
https://dexplorer.ark.io:8443/api/v2/blocks?orderBy=height:
https://dexplorer.ark.io:8443/api/v2/blocks?orderBy=height:descc

**Expected behavior**

Error gracefully or fallback to default values.

**Comment by JeremiGendron** [comment]
dibs

**Comment by dated** [comment]
Fixed with #1282
