### ISSUE TITLE
core-forger

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/core#1333]
https://github.com/ArkEcosystem/core/blob/db42a0312d6d5222c3f4acd1e55127a8fd87d2ef/packages/core-forger/lib/client.js#L33

Shouldn't this be `/internal/block` not `/internal/blocks` ?

**Comment by supaiku0** [comment]
No, that's correct. See https://github.com/ArkEcosystem/core/blob/9668b161a9ed40035f61e6174bfee7e967b1d11b/packages/core-p2p/lib/server/versions/internal/index.js#L22

**Comment by supaiku0** [comment]
Kinda related, maybe the reason why you asked: #1334

**Comment by zillionn** [comment]
Exactly.
