### ISSUE TITLE
More descriptive fork logging

### ISSUE THREAD

**Issue by vRobM** [ArkEcosystem/core#1338]
**Is your feature request related to a problem? Please describe.**
It's difficult to tell what is happening with your node and the network when the network is split or forked.

**Describe the solution you'd like**
Provide enhanced log messaging that indicates the current status of the network according to your node, in a concise (copypasta) way, including number of peers x of y, quorum a of b, and anything else the node knows and can be helpful to **delegates** in troubleshooting.

**Comment by faustbrian** [comment]
The logging already provides information about the quorum and whatnot, if you think this can be improved feel free to send a PR.
