### ISSUE TITLE
Add safe writes to core configuration files

### ISSUE THREAD

**Issue by vRobM** [ArkEcosystem/core#1340]
**Is your feature request related to a problem? Please describe.**
important core configuration files may be overwritten & corrupted if there's an issue with the kernel/filesystem

**Describe the solution you'd like**
implement safe writes to disk, write to temp file, check file, then copy over, keeping one backup.

**Describe alternatives you've considered**
keep config contents in memory and don't assume on disk config is good in case it corrupts. run w/ good config until normal operation can be resumed.

**Comment by faustbrian** [comment]
If your kernel or filesystem get corrupted you have bigger issues then your node not properly running anymore.

Might revisit this in the future if it ever becomes a major issue.
