### ISSUE TITLE
Forger forks in multiforger configuration

### ISSUE THREAD

**Issue by vRobM** [ArkEcosystem/core#1341]
**Describe the bug**
Single node, delegate config with 2 passphrases for the **same** delegate1 to test doubleforging, no issues.
Single node, delegate config with 2 passphrases for the **same** delegate1 + 1 different passphrase for delegate2 to test multiforging, node forks with 0 quorum when forging delegate1 but **not** delegate2.

**Expected behavior**
Both delegate1 and delegate2 should forge normally.
core should detect duplicate secrets.

**Additional context**
Removing 1 passphrase for delegate1 resumes forging for both.

Why does a duplicate secret work until an additional is added?

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/core/commit/ba930d61fffeae27f7dd301e89482c4be4f6fa4d
