### ISSUE TITLE
Add check for crypto verified upon loading transaction from pool db

### ISSUE THREAD

**Issue by kristjank** [ArkEcosystem/core#1349]
**Is your feature request related to a problem? Please describe.**
Add check for crypto verified upon loading transaction from pool db to memory.

**Describe the solution you'd like**
When loading transactions from local storage db - check if crypto verify was a success. The 
`const trx = new Transaction()` sets flag `verified`

**Describe alternatives you've considered**
Similar functionality i used when entering the pool here: https://github.com/ArkEcosystem/core/blob/develop/packages/core-transaction-pool/lib/guard.js#L131-L133

**Comment by vasild** [comment]
How could a transaction enter the pool as valid and somehow become invalid later?

**Comment by kristjank** [comment]
malicious local actor.
