### ISSUE TITLE
core-transaction-pool: dynamicfee-matcher.js

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/core#1351]
https://github.com/ArkEcosystem/core/blob/develop/packages/core-transaction-pool/lib/utils/dynamicfee-matcher.js

I don't like the logic in this file. Imo it should be `if(feeConstants.dynamic) === true` and `else` static. Also inside `dynamic` the static fees should be completely ignored:
https://github.com/ArkEcosystem/core/blob/a07be2a12a9a73847fc453fa1c7732b9efd0bbdc/packages/core-transaction-pool/lib/utils/dynamicfee-matcher.js#L35-L38
What if my dynamic fee is higher than the static? This check will reject all trxs.

To prevent trxs with a very high fee, how about to add `config.delegates.dynamicFees.maxAcceptableFee`?

**Comment by zillionn** [comment]
Also I'm not getting something else. 
https://github.com/ArkEcosystem/core/blob/cb5f6e81e50b2e953344e2905afd4c50740f23ab/packages/core-transaction-pool/lib/utils/dynamicfee-matcher.js#L25
How exactly the relay will know the `minAcceptableFee` if I'm not a forger, don't have `delegates.json` file?

[relay-error.txt](https://github.com/ArkEcosystem/core/files/2566281/relay-error.txt)

I'm not sure that my solution (https://github.com/ArkEcosystem/core/issues/945) is the best, but how about when updating the delegates list, get also their min fees and have it in the memory, so this way the relay will know all delegates min fees?

**Comment by vasild** [comment]
Good questions. Beware that you have raised to issues in one bug report.

The first one is going to be fixed in https://github.com/ArkEcosystem/core/pull/1353
It does not make any sense to introduce a max-fee config knob as then all delegates will set it to 999999999999999999999.

The second issue you raised - we should have a minimum fee config knobs that are also viable for relay nodes.

**Comment by zillionn** [comment]
> It does not make any sense to introduce a max-fee config knob as then all delegates will set it to 999999999999999999999.

Well even now the delegates who want to hurt can always just comment that max fee check...

**Comment by vasild** [comment]
I wouldn't use the word "hurt" for prioritizing higher fee transactions over lower fee ones.

**Comment by zillionn** [comment]
What I meant is that this check is to not accept trxs send with very high fee by mistake. A "good" delegate should set `maxAcceptableFee`, while a "bad" one will accept it to get them moneys.

Also, this is an open source blockchain and main goal is get many bridged chains. Such features are always good imo.

**Comment by zillionn** [comment]
Oh, and your PR https://github.com/ArkEcosystem/core/pull/1353 doesn't solve my first issue. You're still using `config.delegates.dynamicFees.minAcceptableFee` which I believe is only for the forger/delegate, if I'm running only a relay, I don't use that setting.

**Comment by faustbrian** [comment]
I think the `maxAcceptableFee` property isn't a core issue but rather a UI/End-User issue. UI/End-User integrations should take care of making sure the user selects the right fees and warn the user that he is about to select a fee that exceeds the static fees.

If someone wishes to pay 100 ARK as a fee for a transaction that is their decision, core should only care about validating and processing the transaction. If it has a 100 ARK fee and is valid the transaction is good to go.
