### ISSUE TITLE
Configuration Watcher for dynamic refresh

### ISSUE THREAD

**Issue by paroxysm** [ArkEcosystem/core#1373]
**Is your feature request related to a problem? Please describe.**
This feature can be useful especially in dynamic fees to enable changing them w/o having to restart your relay every time. We can then expose modifying the configs via a GUI or CLI interface to make it user-friendly

**Describe the solution you'd like**
The basic idea is that the core registers a file watcher on configuration files and upon a change, it'll re-source those properties.
The file watcher should leverage the event-emitter to fire a 'configuration change' event, to maintain single responsibility principle.

**Comment by faustbrian** [comment]
This is something that is already on the to-do list for 2.1 with many other changes for configuration.
