### ISSUE TITLE
Check if forging is allowed

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/core#1385]
There is again something wrong with the devnet and not sure if this is the problem, but looking at the logs I always got `quorum: 0` because `isForgingAllowed()` returns `false`.

I don't like how this check is done:
https://github.com/ArkEcosystem/core/blob/2a069da20dcdee52dec864ac0edc486ad39f3820/packages/crypto/lib/crypto/slots.js#L142-L148

How about to change it to something like:
`epochTime % this.getConstant('blocktime') < this.getConstant('blocktime') / 2`

**Comment by paroxysm** [comment]
This does seem like a more straight-forward formula to serve the same purpose.

**Comment by zillionn** [comment]
My 2 delegates are running with that code for about 20 hours and haven't missed a single block.

**Comment by paroxysm** [comment]
Create a PR sir.
