### ISSUE TITLE
Relay sync period

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/core#1392]
I've installed `ark-core` on my home computer and started only the relay on devnet. For some reason it is downloading the new blocks in batches every 60 seconds.

[relay.log](https://github.com/ArkEcosystem/core/files/2582552/relay.log)

**Comment by dated** [comment]
Is the port open? Looks like your node isn't receiving any blocks.

**Comment by zillionn** [comment]
It is receiving them, but every 60 seconds. However, it is probably my home comp, because I'm behind routers, firewalls...

**Comment by dated** [comment]
It's _fetching_ them every 60 seconds ;)
