### ISSUE TITLE
Transaction pool empty after restart

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/core#1412]
**Describe the bug**
I have 40 transactions in the pool:
`{"meta":{"count":40,"pageCount":1,"totalCount":40,"next":null,"previous":null,"self":"/api/v2/transactions/unconfirmed?page=1&limit=100","first":"/api/v2/transactions/unconfirmed?page=1&limit=100","last":"/api/v2/transactions/unconfirmed?page=1&limit=100"}`

After restart 0:
`{"meta":{"count":0,"pageCount":0,"totalCount":0,"next":null,"previous":null,"self":"/api/v2/transactions/unconfirmed?page=1&limit=100","first":"/api/v2/transactions/unconfirmed?page=1&limit=100","last":null},"data":[]}`

However, my sqlite file is not empty:

> $ ll ~/.ark/database/
total 856
drwxrwxr-x 2 darknodeuser darknodeuser   4096 Nov 15 19:07 ./
drwxrwxr-x 6 darknodeuser darknodeuser   4096 Nov 15 12:39 ../
-rw-rw-r-- 1 darknodeuser darknodeuser 331776 Nov 15 19:07 transaction-pool-devnet.sqlite
-rw-rw-r-- 1 darknodeuser darknodeuser  32768 Nov 16 12:55 transaction-pool-devnet.sqlite-shm
-rw-rw-r-- 1 darknodeuser darknodeuser 502672 Nov 16 12:28 transaction-pool-devnet.sqlite-wal

**Comment by vasild** [comment]
Hi,

the presence of the -shm and -wal files means that the sqlite connection was not properly closed. If it is, then they will be removed. Maybe the node was not shut down gracefully and did not had a chance to save the data on disk?

Don't expect the .sqlite file to have size of 0 bytes. At least, it contains the table definition. Use
`echo 'select count(*) from pool;' |sqlite3 ~/.ark/database/transaction-pool-devnet.sqlite`
if that is 0 when the node is stopped, then it means no data was saved on disk and the problem is somewhere during shutdown. If >0 then the problem is in the startup code.

**Comment by zillionn** [comment]
> $ pm2 stop all
$ rm -rf ~/.ark/database/*
$ pm2 start all
$ ll ~/.ark/database/
total 60
drwxrwxr-x 2 darknodeuser darknodeuser  4096 Nov 17 00:12 ./
drwxrwxr-x 6 darknodeuser darknodeuser  4096 Nov 15 12:39 ../
-rw-rw-r-- 1 darknodeuser darknodeuser  4096 Nov 17 00:12 transaction-pool-devnet.sqlite
-rw-rw-r-- 1 darknodeuser darknodeuser 32768 Nov 17 00:12 transaction-pool-devnet.sqlite-shm
-rw-rw-r-- 1 darknodeuser darknodeuser 12392 Nov 17 00:12 transaction-pool-devnet.sqlite-wal
$ ~/ark-core/packages/core-tester-cli/bin/tester transfer --skip-validation --base-url http://127.0.0.1 -p "passphrase" -a 0.00000001 --transfer-fee 0.00000270 -n 40 --smart-bridge 'spam'
$ ~/ark-core/packages/core-tester-cli/bin/tester transfer --skip-validation --base-url http://127.0.0.1 -p "passphrase" -a 0.00000001 --transfer-fee 0.00000270 -n 40 --smart-bridge 'spam'
$ ~/ark-core/packages/core-tester-cli/bin/tester transfer --skip-validation --base-url http://127.0.0.1 -p "passphrase" -a 0.00000001 --transfer-fee 0.00000270 -n 40 --smart-bridge 'spam'
$ curl -s http://127.0.0.1:4003/api/v2/transactions/unconfirmed | jq -r '.meta'
{
  "count": 100,
  "pageCount": 2,
  "totalCount": 123,
  "next": "/api/v2/transactions/unconfirmed?page=2&limit=100",
  "previous": null,
  "self": "/api/v2/transactions/unconfirmed?page=1&limit=100",
  "first": "/api/v2/transactions/unconfirmed?page=1&limit=100",
  "last": "/api/v2/transactions/unconfirmed?page=2&limit=100"
}
$ echo 'select count( * ) from pool;' |sqlite3 ~/.ark/database/transaction-pool-devnet.sqlite
0
$ pm2 stop all
$ ll
total 60
drwxrwxr-x 2 darknodeuser darknodeuser  4096 Nov 17 00:22 ./
drwxrwxr-x 6 darknodeuser darknodeuser  4096 Nov 15 12:39 ../
-rw-rw-r-- 1 darknodeuser darknodeuser  4096 Nov 17 00:22 transaction-pool-devnet.sqlite
-rw-rw-r-- 1 darknodeuser darknodeuser 32768 Nov 17 00:22 transaction-pool-devnet.sqlite-shm
-rw-rw-r-- 1 darknodeuser darknodeuser 12392 Nov 17 00:22 transaction-pool-devnet.sqlite-wal
$ echo 'select count(*) from pool;' |sqlite3 ~/.ark/database/transaction-pool-devnet.sqlite
0

**Comment by zillionn** [comment]
On my other server:

> $ echo 'select count(*) from pool;' |sqlite3 ~/.ark/database/transaction-pool-devnet.sqlite
512
$ curl -s http://127.0.0.1:4003/api/v2/transactions/unconfirmed | jq -r '.meta'
{
  "count": 100,
  "pageCount": 4,
  "totalCount": 320,
  "next": "/api/v2/transactions/unconfirmed?page=2&limit=100",
  "previous": null,
  "self": "/api/v2/transactions/unconfirmed?page=1&limit=100",
  "first": "/api/v2/transactions/unconfirmed?page=1&limit=100",
  "last": "/api/v2/transactions/unconfirmed?page=4&limit=100"
}
$ pm2 stop all
$ echo 'select count(*) from pool;' |sqlite3 ~/.ark/database/transaction-pool-devnet.sqlite
512
$ pm2 start all
$ curl -s http://127.0.0.1:4003/api/v2/transactions/unconfirmed | jq -r '.meta'
{
  "count": 0,
  "pageCount": 0,
  "totalCount": 0,
  "next": null,
  "previous": null,
  "self": "/api/v2/transactions/unconfirmed?page=1&limit=100",
  "first": "/api/v2/transactions/unconfirmed?page=1&limit=100",
  "last": null
}
$ echo 'select count(*) from pool;' |sqlite3 ~/.ark/database/transaction-pool-devnet.sqlite
0
$ ll ~/.ark/database/
total 832
drwxrwxr-x 2 darknodeuser darknodeuser   4096 Nov 17 00:35 ./
drwxrwxr-x 6 darknodeuser darknodeuser   4096 Nov 11 16:53 ../
-rw-rw-r-- 1 darknodeuser darknodeuser 655360 Nov 17 00:35 transaction-pool-devnet.sqlite
-rw-rw-r-- 1 darknodeuser darknodeuser  32768 Nov 17 00:35 transaction-pool-devnet.sqlite-shm
-rw-rw-r-- 1 darknodeuser darknodeuser 152472 Nov 17 00:35 transaction-pool-devnet.sqlite-wal

0 rows but 655kb file... Something is off here.

**Comment by zillionn** [comment]
Found the problem #1421
