### ISSUE TITLE
P2P getting txs could fail for > 100 tx block header

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/core#1428]
**Describe the bug**
If a block header is received, it gets all transaction objects related to that header based on the ids. It does this [here](https://github.com/ArkEcosystem/core/blob/develop/packages/core-p2p/lib/server/versions/1/handlers.js#L245). The problem occurs [here](https://github.com/ArkEcosystem/core/blob/develop/packages/core-p2p/lib/server/versions/1/handlers.js#L117) because a block can contain 150 transactions, whereas we are only looking at the first 100 ids. This will then result in a second API request ([here](https://github.com/ArkEcosystem/core/blob/develop/packages/core-p2p/lib/server/versions/1/handlers.js#L248)) on the peer which will likely fail since v2 api has a different port to p2p.

*This is untested, but I wanted someone to check it*

**Expected behavior**
The slice for `getTransactionsFromIds` should be 0 to `config.maxTransactions` I believe.

**Comment by vasild** [comment]
@fix ?

**Comment by vasild** [comment]
The `split(0, 100)` code originates from:

```
commit 62d4f6f2
Parent: 6c6540f4
Author:     fix <fx.thoorens@gmail.com>
AuthorDate: Thu Jan 18 15:50:34 2018 +0100
Commit:     fix <fx.thoorens@gmail.com>
CommitDate: Thu Jan 18 15:50:34 2018 +0100

    completed get transactions

...

+  getTransactionsFromIds (req, res, next) {
+    const txids = req.query.ids.split(',').slice(0, 100).filter(id => id.match('[0-9a-fA-F]{32}'))
+    blockchain.getInstance().getDb().getTransactionsFromIds(txids).then(transactions => {
+      res.send(200, {
+        success: true,
+        transactions: transactions
+      })
+      next()
+    })
+    .catch(error => res.send(500, {success: false, message: error}))
+  }
```

**Comment by alexbarnsley** [comment]
To be fair this may not have been an issue back then with 50 txs per block. But we're now going past that.
