### ISSUE TITLE
p2p API rate limit

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/core#1433]
https://github.com/ArkEcosystem/core/blob/829a43b370eae4c2865fad80ae6e8267f4425f70/packages/core-p2p/lib/defaults.js#L22

I don't see `userCache.expiresIn` here, isn't the default `600000` (10 minutes)?

**Comment by faustbrian** [comment]
Thanks, must have missed that.

Lowered it to 1 minute in https://github.com/ArkEcosystem/core/commit/d0be57584c17f30b4384368570235626a2aa30b4.

**Comment by zillionn** [comment]
And also how about 15/sec not 1000/min? Because I can send 1000 request very fast.
