### ISSUE TITLE
Cannot download blocks error

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/core#1437]
> 0|ark-core-relay  | [2018-11-19 19:43:43][DEBUG]                      : Cannot download blocks from peer http://145.239.93.176:4002 - { Error: timeout of 10000ms exceeded
0|ark-core-relay  |     at createError (/home/darknodeuser/ark-core/node_modules/axios/lib/core/createError.js:16:15)
0|ark-core-relay  |     at Timeout.handleRequestTimeout [as _onTimeout] (/home/darknodeuser/ark-core/node_modules/axios/lib/adapters/http.js:216:16)
0|ark-core-relay  |     at ontimeout (timers.js:436:11)
0|ark-core-relay  |     at tryOnTimeout (timers.js:300:5)
0|ark-core-relay  |     at listOnTimeout (timers.js:263:5)
0|ark-core-relay  |     at Timer.processTimers (timers.js:223:10)
0|ark-core-relay  |   config:
0|ark-core-relay  |    { adapter: [Function: httpAdapter],
0|ark-core-relay  |      transformRequest: [Object],
0|ark-core-relay  |      transformResponse: [Object],
0|ark-core-relay  |      timeout: 10000,
0|ark-core-relay  |      xsrfCookieName: 'XSRF-TOKEN',
0|ark-core-relay  |      xsrfHeaderName: 'X-XSRF-TOKEN',
0|ark-core-relay  |      maxContentLength: -1,
0|ark-core-relay  |      validateStatus: [Function: validateStatus],
0|ark-core-relay  |      headers: [Object],
0|ark-core-relay  |      method: 'get',
0|ark-core-relay  |      params: [Object],
0|ark-core-relay  |      url: 'http://145.239.93.176:4002/peer/blocks',
0|ark-core-relay  |      data: undefined },
0|ark-core-relay  |   code: 'ECONNABORTED',
0|ark-core-relay  |   request:
0|ark-core-relay  |    Writable {
0|ark-core-relay  |      _writableState: [WritableState],
0|ark-core-relay  |      writable: true,
0|ark-core-relay  |      _events: [Object],
0|ark-core-relay  |      _eventsCount: 2,
0|ark-core-relay  |      _maxListeners: undefined,
0|ark-core-relay  |      _options: [Object],
0|ark-core-relay  |      _redirectCount: 0,
0|ark-core-relay  |      _redirects: [],
0|ark-core-relay  |      _requestBodyLength: 0,
0|ark-core-relay  |      _requestBodyBuffers: [],
0|ark-core-relay  |      _onNativeResponse: [Function],
0|ark-core-relay  |      _currentRequest: [ClientRequest],
0|ark-core-relay  |      _currentUrl:
0|ark-core-relay  |       'http://145.239.93.176:4002/peer/blocks?lastBlockHeight=785218' },
0|ark-core-relay  |   response: undefined }

**Comment by faustbrian** [comment]
This is normal that it includes the error stack when the block download fails as it is a debug message.
