### ISSUE TITLE
Trying to add a transaction that is already in the pool

### ISSUE THREAD

**Issue by vasild** [ArkEcosystem/core#1438]
1|ark-core-relay | [2018-11-19 19:16:17][DEBUG] : Transaction pool: ignoring attempt to add a transaction that is already in the pool, id: 2e28df16e0272055ab3aa4d5a4bf9159c1bb7eb4372c2357abae91142955f353

Is sometimes printed at high loads.

This should be studied and understood - some places that call the pool's `addTransactions()` do have a check if the transaction is in the pool and shouldn't lead to this protection kicking in. Other places do not check if the transaction is in the pool.

If it is acceptable for `addTransactions()` to receive a transaction that is already in the pool, then just ignore it without spamming the log with unnecessary information. If it is not acceptable, then fix the code to avoid it and maybe throw an exception from `addTransactions()` if it happens.

**Comment by zillionn** [comment]
<img width="572" alt="screenshot 2018-11-19 at 22 07 42" src="https://user-images.githubusercontent.com/3462869/48732205-a03d3880-ec47-11e8-8abd-77d73674ad17.png">

**Comment by vasild** [comment]
Must have been fixed by recent changes. Closing for now, reopen if seen again.
