### ISSUE TITLE
Testing with core-test-util

### ISSUE THREAD

**Issue by PHANTOM-DEV1** [ArkEcosystem/core#1452]
@alexbarnsley I am trying to run unit test on `core-blockchain` repo, it uses `core-test-util` 's testnet configuration file to set up container.
Current `node_modules` don't have required libraries, so it fails at resolving values from container.
Please let me know how to proceed.

Thanks

**Comment by alexbarnsley** [comment]
@PHANTOM-DEV1 have you done `lerna bootstrap` in the root of core? E.g. `cd ~/ark-core && lerna bootstrap`. You must have lerna installed (see [here](https://docs.ark.io/guidebook/core/development.html#getting-started-with-lerna))

**Comment by PHANTOM-DEV1** [comment]
It worked. Thanks!
