### ISSUE TITLE
Call to unknown function in handler

### ISSUE THREAD

**Issue by wownmedia** [ArkEcosystem/core#1459]
**Describe the bug**
`1|ark-core-relay  | Debug: internal, implementation, error 
1|ark-core-relay  |     TypeError: result.getBroadcastTransactions is not a function
1|ark-core-relay  |     at handler (/home/ark/ark-core/packages/core-p2p/lib/server/versions/1/handlers.js:335:39)`

**To Reproduce**
Passed by in logs.

**Comment by supaiku0** [comment]
Thanks! Fixed in #1458
