### ISSUE TITLE
Network does not adapt to diverse maxTransactionsPerRequest settings

### ISSUE THREAD

**Issue by vasild** [ArkEcosystem/core#1464]
Each relay node has a setting maxTransactionsPerRequest which determines the maximum number of transactions it would accept in one request. If an acceptable request is received with N transactions (N <= maxTransactionsPerRequest) it is broadcasted to other peers also as one request with N transactions.

This is a problem if the recipient of the broadcast has set maxTransactionsPerRequest to a value smaller than N. Then the entire request is rejected and no attempt is made by the sending peer to adapt and send less transactions per request to the recipient.

To fix this:
* The rejection should contain a hint as to what is the maximum accepted. E.g. "You sent me 200, but I would accept maximum 160 per request".
* The broadcaster should interpret that, reduce the number of transactions in the request and retry.

**Comment by zillionn** [comment]
Why do this and send several requests, when the receiver can just slice the request and accept only as much as it's `maxTransactionsPerRequest`?

**Comment by zillionn** [comment]
Oh, you'll send requests until the other relay gets all the txs?
