### ISSUE TITLE
Improve logs readability

### ISSUE THREAD

**Issue by vasild** [ArkEcosystem/core#1514]
Currently logs look like:

```
1|ark-core-relay   | [2018-11-26 21:35:03][INFO]                       : Blockchain 100% in sync
```

1. Lots of space is wasted before `:` which makes the lines wrap and impedes readability.

2. It would be useful to print the commit id (aka version) of the software running, so we would avoid having to ask people "Which version did you run?". Even the first 4 chars of the commit id would suffice, e.g. `c1bd`.

3. Some space is wasted before the second `|`. This is probably to have the dates aligned:
```
1|ark-core-relay   | [2018-11-26 21:35:07][INFO]                       : Checking...
2|ark-core-forger  | [2018-11-26 21:35:07][INFO]                       : Fork 6...
2|ark-core-forger  | [2018-11-26 21:35:07][DEBUG]                      : Network...
```
To get the dates aligned without wasting space they can be printed first.

4. It is easier to read when the separator is a single space instead of `[` or `|`.

For example:
```
2018-11-26 21:35:07 INFO 1 ark-core-relay: Checking...
2018-11-26 21:35:07 INFO 2 ark-core-forger: Fork 6...
2018-11-26 21:35:07 DEBUG 2 ark-core-forger: Network...
```

**Comment by vasild** [comment]
5. If every "sender" begins with `ark-core-` then we may as well omit that and have just e.g. `relay` and `forger` instead of `ark-core-relay` and `ark-core-forger`.

**Comment by paroxysm** [comment]
Yes, this would be an invaluable enhancement.

**Comment by vasild** [comment]
6. Print partial transaction ids, e.g. just the first 6 characters.

**Comment by paroxysm** [comment]
That might undermine some log analysis tools(such as ElasticSearch)

**Comment by geopsllc** [comment]
Finally a fix for the horrible inefficiencies in the logs. Do not disregard!

**Comment by geopsllc** [comment]
> 1. If every "sender" begins with `ark-core-` then we may as well omit that and have just e.g. `relay` and `forger` instead of `ark-core-relay` and `ark-core-forger`.

I'm sure some people will be running multiple cores on the same server in the future so removing the token name from the logs would be a problem.

**Comment by paroxysm** [comment]
That isn't recommended. You have to separate processes trying to log into the same file, that's a bad idea and asking for race conditions . For each diff token, they should define a different log location

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/core/commit/cc1c249b171177eb82d0b186c6ef4e9446ec2d64

The rest is subjective and can be handled by custom log formatters if people want to use them, that is the purpose of those formatters, don't like the log - make your own.
