### ISSUE TITLE
Delegate registration unsuccessful

### ISSUE THREAD

**Issue by moazzamak** [ArkEcosystem/core#1531]
**Describe the bug**
Delegate registration doesn't work while using the desktop wallet on devnet. Tested using the V2 1.6.1 desktop client.

**To Reproduce**
1. Create new account on devnet.
2. Recieve dark into account (enough for delegate registration).
2. Attempt to register delegate.
3. See developer console log.

**Expected behavior**
Should be able to register a delegate from new account with received dark.

**Screenshots**
![error](https://user-images.githubusercontent.com/6873275/49152226-7902fd00-f312-11e8-93ec-7cc9552d32dd.png)

**Server (please complete the following information):**
 - OS: Ubuntu
 - Version 16.04

**Additional context**
Can't send out any dark from the wallet either. It seems like some flag is not being polled correctly by the wallet for detecting confirmed transactions.

**Comment by boldninja** [comment]
Closed via #1533
