### ISSUE TITLE
minFeeBroadcast with static fees

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/core#1552]
https://github.com/ArkEcosystem/core/blob/be4d2d688116bd0a2efd9b2f78394a2bd090da51/packages/core-transaction-pool/lib/utils/dynamicfee-matcher.js#L27-L32

So, if I use static fees, txs with lower fees will not be broadcasted at all. Is this intentional?

**Comment by kristjank** [comment]
checking this now...

**Comment by geops22** [comment]
Optimally anything above tx sizeinbytes should be broadcast to the network to avoid edge cases.

**Comment by moazzamak** [comment]
Similar issue was discussed in #945 
I think one temporary solution would be to check if any of the blocks in last round were full. If so then keep the transaction otherwise if all were non-full then remove it from mempool.

**Comment by zillionn** [comment]
@kristjank How about dynamic fees on by default?

**Comment by vasild** [comment]
> So, if I use static fees, txs with lower fees will not be broadcasted at all. Is this intentional?

Yes, of course. This is the very definition of static fees - to accept only fees that equal some predefined constant. See also https://github.com/ArkEcosystem/core/pull/1554#discussion_r238074678

> @kristjank How about dynamic fees on by default?
There you go: https://github.com/ArkEcosystem/core/pull/1555

Cheers!

**Comment by kristjank** [comment]
:) didn't follow before :) lol. Yes ok

**Comment by vasild** [comment]
The code wrt static fees is behaving as intended. Dynamic fees are now the default.
