### ISSUE TITLE
 I tried calling the wallets.bip38.create method twice with the same userId, bip38 value in json rpc. But another wif value came out. 

### ISSUE THREAD

**Issue by leeheejoo** [ArkEcosystem/core#1644]
I tried calling the wallets.bip38.create method twice with the same userId, bip38 value in json rpc. But another wif value came out. From the third call, we get the same wif value. I tested it on devnet.

[testuser@localhost core]$ curl -X POST -H 'Content-Type: application/json' http://127.0.0.1:8080 \
> -d '{
>     "jsonrpc": "2.0",
>     "id": "unique-request-id",
>     "method": "wallets.bip38.create",
>     "params": {
>         "userId": "11aaabba",
>         "bip38": "aaa"
>     }
> }' | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current Dload  Upload   Total   Spent    Left  Speed
100   417  100   248  100   169     12      8  0:00:21  0:00:20  0:00:01    19
{
    "id": "unique-request-id",
    "jsonrpc": "2.0",
    "result": {
        "address": "DMyeYZbGJYvfVaQroT4XPm6R2xwwDbQq42",
        "publicKey": "02f9ee18bb243c5ed3816492a8be582ce5bb23438cb0cbf9f20aaaafa6d5c75aa1",
        "wif": "6PYUbgWicCfvPhhKjMPH5KXnN7p65WRAKkCXw3mNyMKzZZSfj6ZZn7zEBR"
    }
}
[testuser@localhost core]$ curl -X POST -H 'Content-Type: application/json' http://127.0.0.1:8080 -d '{
    "jsonrpc": "2.0",
    "id": "unique-request-id",
    "method": "wallets.bip38.create",
    "params": {
        "userId": "11aaabba",
        "bip38": "aaa"
    }
}' | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current Dload  Upload   Total   Spent    Left  Speed
100   411  100   242  100   169     20     14  0:00:12  0:00:11  0:00:01    19
{
    "id": "unique-request-id",
    "jsonrpc": "2.0",
    "result": {
        "address": "DMyeYZbGJYvfVaQroT4XPm6R2xwwDbQq42",
        "publicKey": "02f9ee18bb243c5ed3816492a8be582ce5bb23438cb0cbf9f20aaaafa6d5c75aa1",
        "wif": "SHiGzF6cogSHv63LFrv62V5nRcNBUWNJ8DpKjMEjeGVrFvje7e3q"
    }
}

[testuser@localhost core]$ curl -X POST -H 'Content-Type: application/json' http://127.0.0.1:8080 -d '{
    "jsonrpc": "2.0",
    "id": "unique-request-id",
    "method": "wallets.bip38.create",
    "params": {
        "userId": "11aaabba",
        "bip38": "aaa"
    }
}' | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   411  100   242  100   169     23     16  0:00:10  0:00:10 --:--:--    17
{
    "id": "unique-request-id",
    "jsonrpc": "2.0",
    "result": {
        "address": "DMyeYZbGJYvfVaQroT4XPm6R2xwwDbQq42",
        "publicKey": "02f9ee18bb243c5ed3816492a8be582ce5bb23438cb0cbf9f20aaaafa6d5c75aa1",
        "wif": "SHiGzF6cogSHv63LFrv62V5nRcNBUWNJ8DpKjMEjeGVrFvje7e3q"
    }
}

**Comment by faustbrian** [comment]
You can see in the old RPC https://github.com/ArkEcosystem/rpc-server/blob/master/src/account.js#L68-L107 and new RPC https://github.com/ArkEcosystem/core/blob/master/packages/core-json-rpc/lib/server/methods/wallets/bip38/create.js#L8-L38 why they differ between the first and subsequent requests.

**Comment by leeheejoo** [comment]
I called new rpc (json rpc) three times with the same userId and bip38. Every time I create a new account, the wif values ​​for the first call and the second call are different.
 So I added the log to https://github.com/ArkEcosystem/core/blob/master/packages/core-json-rpc/lib/server/methods/wallets/bip38/create.js to see the results.
 The first is to call the error handling scope where the exception occurred, and the second is to call the try scope correctly. However, the wif value is different.


const Joi = require('joi')
const { crypto, utils } = require('@arkecosystem/crypto')
const bip39 = require('bip39')
const bip38 = require('bip38')
const database = require('../../../services/database')
const getBIP38Wallet = require('../../../utils/bip38-keys')
//add
const logger = require('@arkecosystem/core-container').resolvePlugin('logger')

module.exports = {
  name: 'wallets.bip38.create',
  async method(params) {
    try {
      const { keys, wif } = await getBIP38Wallet(params.userId, params.bip38)

      //add
      logger.error(`wallets.bip38.create success: wif => ${wif}, publicKey => ${keys.publicKey}`)

      return {
        publicKey: keys.publicKey,
        address: crypto.getAddress(keys.publicKey),
        wif,
      }
    } catch (error) {
      const { publicKey, privateKey } = crypto.getKeys(bip39.generateMnemonic())

      const encryptedWif = bip38.encrypt(
        Buffer.from(privateKey, 'hex'),
        true,
        params.bip38 + params.userId,
      )
      await database.set(
        utils.sha256(Buffer.from(params.userId)).toString('hex'),
        encryptedWif,
      )

      //add
      logger.error(`wallets.bip38.create error: wif => ${encryptedWif}, publicKey => ${publicKey}, error => ${JSON.stringify(error)}`)

      return {
        publicKey,
        address: crypto.getAddress(publicKey),
        wif: encryptedWif,
      }
    }
  },
  schema: {
    bip38: Joi.string().required(),
    userId: Joi.string()
      .hex()
      .required(),
  },
}







[2018-12-05 19:15:59][INFO]    : Block download finished 🚀
[2018-12-05 19:15:59][DEBUG]   : event 'PROCESSFINISHED': {"syncWithNetwork":"downloadFinished"} -> {"syncWithNetwork":"processFinished"} -> actions: [checkLastBlockSynced]
[2018-12-05 19:15:59][DEBUG]   : event 'SYNCED': {"syncWithNetwork":"processFinished"} -> {"syncWithNetwork":"end"} -> actions: [syncingComplete]
[2018-12-05 19:15:59][INFO]    : Blockchain 100% in sync 💯
[2018-12-05 19:15:59][DEBUG]   : event 'SYNCFINISHED': {"syncWithNetwork":"end"} -> "idle" -> actions: [checkLater, blockchainReady]
[2018-12-05 19:16:23][ERROR]   : wallets.bip38.create error: wif => 6PYLYgfjCofgvNqoUBjb9HGhNoFE9ouFJDQDpB65US9vSHzZnXD4e4CZiG, publicKey => 021632158eb155021a7b922669876cbf630ddc5ed3d9ff728aa36fe2719759192d, error => {}
[2018-12-05 19:16:35][ERROR]   : wallets.bip38.create success: wif => SDjQz1d5gBsPYX3hx7SC8M1KXcY2jNNeMfQn9Up7xHEztaUANUL5, publicKey => 021632158eb155021a7b922669876cbf630ddc5ed3d9ff728aa36fe2719759192d
[2018-12-05 19:16:59][DEBUG]   : event 'WAKEUP': "idle" -> {"syncWithNetwork":"syncing"} -> actions: [checkLastDownloadedBlockSynced]
[2018-12-05 19:16:59][DEBUG]   : Queued blocks (rebuild: 0 process: 0)

**Comment by zillionn** [comment]
It's a bug. First time you run the query, there is no `encryptedWif` in the database:
https://github.com/ArkEcosystem/core/blob/6518001679ed9a08924e36c33474c5305fd78dae/packages/core-json-rpc/lib/server/utils/bip38-keys.js#L8-L10

and the `catch` is returning `encryptedWif` not encoded:
https://github.com/ArkEcosystem/core/blob/6518001679ed9a08924e36c33474c5305fd78dae/packages/core-json-rpc/lib/server/methods/wallets/bip38/create.js#L20-L36

@leeheejoo Can you test this PR #1652 ?

**Comment by leeheejoo** [comment]
I confirmed that it works correctly.
