### ISSUE TITLE
Creating a genesisBlock data

### ISSUE THREAD

**Issue by tiagor0424** [ArkEcosystem/core#1657]
Hi, @alexbarnsley 
I am tring to create test genesisBlock data.
What script can I use?
I want to create my own.

Thanks

**Comment by tiagor0424** [comment]
@alexbarnsley Would be good if I can create genesis data from existing wallet information.

**Comment by alexbarnsley** [comment]
@tiagor0424 you can create a genesis block using the core-deployer package:

```
cd ~/ark-core/packages/core-deployer
./bin/deployer --network mainnet --name new --p2pPort 4102 --apiPort 4103
```

You can see all the options available here:

https://github.com/ArkEcosystem/core/blob/master/packages/core-deployer/bin/deployer#L22-L107

Regarding from existing data, it's unlikely we'll do that anytime soon as there's no real need for that. I'm happy if someone from the community wants to take a look at it, but for us it's low priority I think.
