### ISSUE TITLE
API endpoint not available

### ISSUE THREAD

**Issue by Moustikitos** [ArkEcosystem/core#1671]
**Describe the bug**
API endpoint not available

**To Reproduce**
check this two links
https://explorer.ark.io:8443/api/v2/delegates/03b6dbf2a9b8a94d41f1e2a6bb03bb385b08f51565ff13ea56ce1b26c6cce377c7/blocks
http://178.32.65.142:4003/api/v2/delegates/03b6dbf2a9b8a94d41f1e2a6bb03bb385b08f51565ff13ea56ce1b26c6cce377c7/blocks

It seems that only `https://explorer.ark.io:8443` gives access to the `api/v2/delegates/{publicKey}/blocks` endpoint

**Comment by faustbrian** [comment]
The second server runs on very low-tier specs which are not meant to be used to serve an API with millions of records. This results in code 503 because the endpoint times out.

The explorer server is not a potato, that is why you receive a response there.

**Comment by Moustikitos** [comment]
I'm running a node with a nice config and i got the same issue 

```>>> rest.GET.api.v2.delegates("03b6dbf2a9b8a94d41f1e2a6bb03bb385b08f51565ff13ea56ce1b26c6cce377c7", "blocks", peer="http://127.0.0.1:4003")
{'except': True, 'success': False, 'error': 'status code 503 returned'}```

this is equivalent to : `http://127.0.0.1:4003/api/v2/delegates/03b6dbf2a9b8a94d41f1e2a6bb03bb385b08f51565ff13ea56ce1b26c6cce377c7/blocks`
