### ISSUE TITLE
[100$] 100% coverage for core-http-utils

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/core#1763]
If you want to take on this task please leave a comment.

**Comment by jdar** [comment]
I'll look into this, to get my toes wet. 

If I have test-architecture questions, I will bug people on slack.

**Comment by jdar** [comment]
I relinquish. This ticket is up for grabs.

**Comment by faustbrian** [comment]
Tests will be receiving in overhaul in Core 3.0, thus closing.
