### ISSUE TITLE
Add pre-packaged Vagrant box to provide a full development environment

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/core#1908]
Same as https://github.com/laravel/homestead which provides a ready-to-go Vagrant box that has everything installed you would need to develop.

**Comment by paroxysm** [comment]
We'd probably wanna outline the requirements we'll need for such as box
VirtualBox is probably a good choice for virtualization needs

- Memory/CPU/OS requirements

1. Ubuntu 16.04, but this isn't a hard requirement. NodeJS will run on many linux distros
2. Atleast 4GB of memory allocated to the VM, the IDE, postgres and relay instances will probably consume quite a bit.
3. At least 2 CPUs allocated to the VM, fast tests.

- Software requirements

1. Git VCS, Ubuntu came with it pre-installed
2. Docker community edition - to quickly spin up/tear down postgres instances used for tests and running relays
3. node and nvm. Nvm to easily manage node versions, useful for regression testing too.
4. postgres tools - useful for interacting with the docker postgres instance(restoring from snapshot for instance)
5. IDE of devs choice - Eclipse, Atom, or Sublime??
