### ISSUE TITLE
Webhook API responses unclear on actual result

### ISSUE THREAD

**Issue by galperins4** [ArkEcosystem/core#1920]
**Describe the bug**
Two of the Webhook endpoints (Update / Delete) just return a no content response (204). This is not ideal as most clients consider no response as a potential error. In addition, I tried to delete a webhook that didn't exist (webhook 2 vs 1) and got the same exact response with a valid delete and a delete that couldn't be processed. At least a success message should be passed back to let a client know if the request was processed or not. 

**To Reproduce**
1. Subscribe to a new webhook
2. Use client/api request to either update or delete webhook
3. Receive no content response (204)

**Expected behavior**
At minimum the endpoints should return a success or fail json response. 

**Server (please complete the following information):**
 - OS: Ubuntu
 - Version: 18.04

**Comment by faustbrian** [comment]
204 is not considered an error by any client, if they do so it is an implementation failure as it isn't in the 400 or 500 range.

204 is commonly used for modification actions that contain no response so it is correct that this code is returned.

https://httpstatuses.com/204
