### ISSUE TITLE
Cannot find module '@arkecosystem/core-config'

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/core#1921]
OS: Ubuntu 18.4
Core: d7d74bcd

I get this error when restart the core:

> 1|ark-core | { Error: Cannot find module '@arkecosystem/core-config'
1|ark-core |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
1|ark-core |     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
1|ark-core |     at Module.require (internal/modules/cjs/loader.js:637:17)
1|ark-core |     at require (internal/modules/cjs/helpers.js:22:18)
1|ark-core |     at PluginRegistrar.__resolve (/home/darknodeuser/ark-core/packages/core-container/src/registrars/plugin.ts:177:24)
1|ark-core |     at PluginRegistrar.__registerWithContainer (/home/darknodeuser/ark-core/packages/core-container/src/registrars/plugin.ts:79:32)
1|ark-core |     at PluginRegistrar.register (/home/darknodeuser/ark-core/packages/core-container/src/registrars/plugin.ts:69:21)
1|ark-core |     at PluginRegistrar.setUp (/home/darknodeuser/ark-core/packages/core-container/src/registrars/plugin.ts:36:24)
1|ark-core |     at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }

**Comment by faustbrian** [comment]
Was removed, just remove it from your `~/.ark/config/plugins.js` file and restart.
