### ISSUE TITLE
Clean up the use of dcodeIO/bytebuffer.js

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/core#1932]
Right now the use of the `ByteBuffer` lib is pretty messy and can be cleaned up quite a bit.

Offsets are specified manually like seen here https://github.com/ArkEcosystem/core/blob/develop/packages/crypto/src/models/transaction.ts#L181. A call to `readInt8` will automatically move the cursor forward 1 byte which means we continue reading at byte 2 so there is no need to manually specify `readInt8(2)`, `readInt8()` will be sufficient.

We are also using native string methods to read things like public keys for which we instead could use `ByteBuffer.readString` to guarantee consistent behaviour based on the offsets per type.

Offsets are automatically set by the library as can be seen in the docs at https://github.com/dcodeIO/bytebuffer.js/wiki/API which means there is no need for us to manually specify any offsets, which reduces the possibility of mistakes.

**Comment by JeremiGendron** [comment]
from my tests:
```ts
buf.readInt8() // returns version OK
buf.readInt8() // returns -1 for network (not OK)
```
but
```ts
buf.readInt8() // OK
buf.readInt8(2) // OK
```

**Comment by supaiku0** [comment]
@JeremiGendron That is because offset 0 contains `0xff` which needs to be accounted for. I'm refactoring part of the crypto models and this issue is on my list.

**Comment by JeremiGendron** [comment]
```ts
clone.readBytes(33).toString("hex") ===  transaction.senderPublicKey = hexString.substring(16, 16 + 33 * 2);
```

stopping now...

**Comment by JeremiGendron** [comment]
https://github.com/JeremiGendron/core/blob/dump/branch/packages/crypto/src/models/transaction.ts#L189

up to Transaction.parseSignatures
