### ISSUE TITLE
[Possible] Broadcast fee too low - both "accepted" and "invalid"

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/core#1937]
**Describe the bug**
I'm not sure if this is an issue or not after speaking to @faustbrian. If the minBroadcastFee is set high, it's possible for the node receiving the transaction to accept it. It's also possible for the transaction to be invalid because it's not able to broadcast. The question is, should it be both accepted and invalid at the same time?

**Comment by zillionn** [comment]
IMO if accepted OR broadcasted shouldn't be invalid.
