### ISSUE TITLE
Generalising the vendor header

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/core#1965]
Is it possible/worthwhile to generalise the vendorName [here](https://github.com/ArkEcosystem/core/blob/master/packages/core-api/lib/defaults.js#L35) so that it doesn't get changed with each fork/chain. We can cater for it in wallets but I think it will be too confusing to users to understand what its intention is even for. The alternative is to allow us to get it somehow, perhaps from the `/config` endpoint. 

To clarify, this is the header sent when making API requests: `application/vnd.ark.core-api.v2+json`

If it is the case that we can generalise, I think we'll need to allow both for a while until devnet is merged with mainnet at least for backwards compatibility, otherwise the desktop wallet will only work on one of the networks.

**Comment by faustbrian** [comment]
I think we should hold off this change until 2.5.0 as that will be a release that introduces a few breaking changes for the API anyways.

**Comment by alexbarnsley** [comment]
What if we could generalise (`core-api`? 🤷‍♂️) now, but also check for `ark.core-api`. and then remove the `ark.core-api` check in 2.5.0? My only concern with doing it in 2.5.0 is that there may be quite a few chains by then. Currently phantom can't be added to the desktop wallet as a v2 network because they changed this to `phantom.core-api`. if we really need to we can add an option on the wallets to change this, it's just a weird thing to non-technical users to have to specify when connecting to a new network. That being said, I don't want to necessarily write/change core around the wallet
