### ISSUE TITLE
Implement replay command to verify blockchain from 0

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/core#1986]
Whenever we make changes that could affect the sync from 0 we manually start one. It would be easier if we would have a command to replay the verification of all data in the database like it is done during sync but without storing the data again.

**tl;dr**
Sync a node from the database without storing any data, basically a dry-run from local data.

-----

**If you want to take on this task please leave a comment.**

**Comment by supaiku0** [comment]
WIP and still hacky, but overall its working: https://github.com/ArkEcosystem/core/tree/blockchain-replay
