### ISSUE TITLE
Transaction pool expiration not working as intended

### ISSUE THREAD

**Issue by supaiku0** [ArkEcosystem/core#1993]
The transaction pool removes any transaction where the timestamp is older than `maxTransactionAge`. Meaning that a valid transaction older than ~45 minutes will still get accepted, but dropped before the transaction is broadcasted. Instead it should check against the time where it entered the pool.

https://github.com/ArkEcosystem/core/blob/5a703df3c2b1f86a7e25a7d39fb2334af4d7b436/packages/core-transaction-pool/src/mem-pool-transaction.ts#L64

https://github.com/ArkEcosystem/core/blob/5a703df3c2b1f86a7e25a7d39fb2334af4d7b436/packages/core-transaction-pool/src/mem.ts#L265

**Comment by supaiku0** [comment]
As discussed this is working as intended after all and we will just increase the `maxTransactionAge`.

**Comment by zillionn** [comment]
IMO @supaiku0 is right. What if you were generating some long list of txs offline and then, 1 hour/day later you broadcast them? They all will be rejected. It doesn't matter when you generated the tx, it matters how long it was staying the pool. The point of `maxTransactionAge` is to have enough time for all delegates to try to forge the tx.
