### ISSUE TITLE
Refactor specifications of transaction rules ?

### ISSUE THREAD

**Issue by Nigui** [ArkEcosystem/core#2015]
I'm currently working on a project where we want to add transaction types. 

After analysing the code, I'm a little bit confused about transaction [format validation](https://github.com/ArkEcosystem/core/tree/master/packages/crypto/lib/validation) (with `joi`).

In `@Arkecosystem/crypto` there are two folders where we can find format specifications:
- `validation/extensions/transactions/`
- `validation/rules/models/transactions/`

Transaction format seems to be validated by [`Engine`](https://github.com/ArkEcosystem/core/blob/master/packages/crypto/lib/validation/engine.js) through [`TransactionValidator`](https://github.com/ArkEcosystem/core/blob/master/packages/crypto/lib/validation/validators/transaction.js).
The `init` method of `Engine` overrides `joi` instance with specifications inside `extensions` folder.
Then, every time `validate` function is called, rules in parameters are also extending `joi`.

If we look where `rules` folder is called, it's in [`Validator`](https://github.com/ArkEcosystem/core/blob/develop/packages/crypto/src/validation/validator.ts#L2). 
But `rules/models` is even [not exported](https://github.com/ArkEcosystem/core/blob/develop/packages/crypto/src/validation/rules/index.ts), so I think that they're never used.  

1. Is there differences between `extensions/transactions` and `rules/models/transactions` or is `rules/models/transations` deprecated ?

2. Is `Validator` still used ? 
3. Does [`TransactionValidator` constructor](https://github.com/ArkEcosystem/core/blob/5b6a51cf93266179cd2ae7e872a46130dc2ad4bd/packages/crypto/lib/validation/validators/transaction.js#L5-L10) re-add transaction rules, even after `Engine.init()` added them ?

**Comment by faustbrian** [comment]
The duplication is a left-over from constant refactoring of the package. `extensions` and `rules` will be merged in an upcoming release to reduce duplication.

**Comment by Nigui** [comment]
Ok so currently, only `extensions` folder is used for transactions ?

**Comment by faustbrian** [comment]
Yeah, should be fine to ignore the `rules/transactions`. @supaiku0 should we get rid of the rules before 2.1?
