### ISSUE TITLE
Define explicit order for loading plugins during startup

### ISSUE THREAD

**Issue by vasild** [ArkEcosystem/core#2034]
**Describe the bug**
Currently plugins are loaded during startup at:
https://github.com/ArkEcosystem/core/blob/develop/packages/core-container/src/registrars/plugin.ts#L35
using [`Object.entries()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries) on a predefined list of plugins, defined at e.g.:
https://github.com/ArkEcosystem/core/blob/develop/packages/core/src/config/devnet/plugins.js

The list is defined as a hash map `{ key1: value1, key2: value2, ... }`. The problem is that the [`Object.entries()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries) method is not guaranteed to return the elements in any specific order, but however we depend on the plugins being loaded in the order they are defined in `plugins.js`.

A possible fix would be to change the hash map in `plugins.js` to an array to preserve the order, or introduce a plugin priority and then sort the array returned by [`Object.entries()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries) by priority.

**Comment by faustbrian** [comment]
Any code to actually reproduce what you think is an issue? Has not occurred in over a year and the below code has 0 issues.

```
const plugins = {
    "@arkecosystem/core-event-emitter": {},
    "@arkecosystem/core-logger-winston": {},
    "@arkecosystem/core-database-postgres": {},
    "@arkecosystem/core-transaction-pool": {},
    "@arkecosystem/core-p2p": {},
    "@arkecosystem/core-blockchain": {},
    "@arkecosystem/core-api": {},
    "@arkecosystem/core-webhooks": {},
    "@arkecosystem/core-graphql": {},
    "@arkecosystem/core-forger": {},
    "@arkecosystem/core-json-rpc": {},
    "@arkecosystem/core-snapshots": {},
};

const expectedString = '[["@arkecosystem/core-event-emitter",{}],["@arkecosystem/core-logger-winston",{}],["@arkecosystem/core-database-postgres",{}],["@arkecosystem/core-transaction-pool",{}],["@arkecosystem/core-p2p",{}],["@arkecosystem/core-blockchain",{}],["@arkecosystem/core-api",{}],["@arkecosystem/core-webhooks",{}],["@arkecosystem/core-graphql",{}],["@arkecosystem/core-forger",{}],["@arkecosystem/core-json-rpc",{}],["@arkecosystem/core-snapshots",{}]]';

for (let i = 0; i < 1000000; i++) {
    if (JSON.stringify(Object.entries(plugins)) !== expectedString) {
        console.log('problem')
    }
}
```

**Comment by vasild** [comment]
Apparently the current versions of Nodejs, for our current case return the entries in the same order as defined in plugins.js.

However the documentation of [Object.entries()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries) explicitly states:

> The order of the array returned by Object.entries() does not depend on how an object is defined. If there is a need for certain ordering then the array needs to be sorted first...

That said, it currently seems to work, but there is no guarantee it will continue working in the future - maybe future versions of Nodejs will return the elements in some other order, or maybe current versions of Nodejs could reorder the elements based on the size of the hash map, maybe order is unchanged for small sets, but once some threshold is crossed (more than N elements), then some internal reordering happens and the `entries()` method returns elements in a different order.

In any case, depending on undocumented behavior is a bad practice as it may change any time.

**Comment by vasild** [comment]
> The docs also state `The ordering of the properties is the same as that given by looping over the property values of the object manually.` which means it has the same order as if we would use the plain object instead of the entries for an iteration.

Yes, and that order is also undefined.

> A breaking change like that to the node.js engine to such a core functionality is nothing more then fantasy, millions of applications would simply be breaking and that release would have to be announced months or years in advance as this is such a basic functionality that is used all over the place.

I wouldn't argue whether such a change would be breaking or not or how many apps are currently broken in a similar way by depending on undocumented behavior. Arguing about that would move the focus of the discussion away from the important thing - **our app depends on undocumented behavior** which is a bug that should be fixed.

**Comment by faustbrian** [comment]
The important thing is that you are spending time on something that is not an issue and most likely will never be.

Just because node.js has their own implementation of the `Object.entries` method doesn't mean that it is a problem and the only way to reproduce it is if you run above code in a dozen different browsers which all have their own implementations as they follow a **recommended** spec. No one is required to 100% implement those specs as they were intended.

**Our concern is if the code works with node.js, which it does without any issues as above code shows, not in the browser or any other environment.**
