### ISSUE TITLE
Implement estimate/count switch for API repository methods

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/core#2110]
**Is your feature request related to a problem? Please describe.**
Right now the methods that are used to query data for the API use estimates rather then count queries due to widespread performance issues caused by people running on low-spec machines.

**Describe the solution you'd like**
Since the count queries are mainly an issue for people running on low-spec machines without considering what kinda resources it takes to constantly query a database with millions of records and count those the simplest solution is to make the count behaviour configurable.

Something as simple as `useEstimates: true/false` should do the trick but making use of that property needs some refactoring in the database repositories after https://github.com/ArkEcosystem/core/pull/2107 is merged because count queries need to be constructed the same way the select queries are constructed to retrieve accurate values.

This will allow low-spec machines to continue to use the API with estimates and slightly inaccurate data _(nature of an estimate)_ while people that run core on decently specced hardware that can handle the extra load caused by constant querying and especially count queries can get accurate data.

**Describe alternatives you've considered**
n/a

**Comment by dated** [comment]
Is this being worked on? There's an assignee and a Bounty Tier - which one is it?

**Comment by faustbrian** [comment]
Removed the assignee, no one is working on it at the moment.

**Comment by faustbrian** [comment]
Closing as a real solution with real counts is looked into.
