### ISSUE TITLE
The `totalCount` of /wallets/<address>/transactions is wrong

### ISSUE THREAD

**Issue by j-a-m-l** [ArkEcosystem/core#2118]
The endpoint counts correctly the transaction of this wallet (`totalCount` is 636):
GET http://142.44.253.192:4003/api/v2/wallets/DSyG9hK9CE8eyfddUoEvsga4kNVQLdw2ve/transactions?orderBy=timestamp:desc&limit=30&page=1

But it doesn't work well with this other (`totalCount` is 50 instead of 89):
GET http://142.44.253.192:4003/api/v2/wallets/D8jk5su4Y5TJtn4ffcg2e9yX48UghB8dwM/transactions?orderBy=timestamp:desc&limit=50&page=1

Other endpoints count correctly the transaction of that wallet (`totalCount` is 89):
POST http://142.44.253.192:4003/api/v2/transactions/search
`{"addresses":["D8jk5su4Y5TJtn4ffcg2e9yX48UghB8dwM"]}`

**Comment by dated** [comment]
FYI https://github.com/ArkEcosystem/core/issues/1903

**Comment by vasild** [comment]
https://github.com/ArkEcosystem/core/pull/2772 made it configurable whether to use estimates (fast) or the precise `COUNT(*)` (slow).
