### ISSUE TITLE
Improve block download peer selection

### ISSUE THREAD

**Issue by supaiku0** [ArkEcosystem/core#2130]
**Is your feature request related to a problem? Please describe.**
Right now we choose a random peer, without taking into account that it may be forked. We can reuse the information from the `PeerVerifier` now to make it smarter.

**Describe the solution you'd like**
Use information gathered from the `PeerVerifier` to make the peer selection a bit less random.

**Describe alternatives you've considered**
n/a

**Comment by vasild** [comment]
https://github.com/ArkEcosystem/core/pull/2137

**Comment by vasild** [comment]
Fixed in https://github.com/ArkEcosystem/core/pull/2137
