### ISSUE TITLE
Improve peer discovery

### ISSUE THREAD

**Issue by supaiku0** [ArkEcosystem/core#2131]
**Is your feature request related to a problem? Please describe.**
Right now we discover peers by downloading a peer list from a single random peer.

**Describe the solution you'd like**
Instead we should query multiple peers to build a peer list.

**Describe alternatives you've considered**
n/a

**Comment by vasild** [comment]
https://github.com/ArkEcosystem/core/pull/2152

**Comment by vasild** [comment]
Done
