### ISSUE TITLE
Don't use native numbers for storing arktoshi

### ISSUE THREAD

**Issue by vasild** [ArkEcosystem/core#2202]
Even though the code uses Bignum for manipulating arktoshi we have `Bignum | number | string` in the definitions of the classes. This is because the unit tests use fixtures/jsons that use numbers, e.g. `amount: 123` instead of `amount: "123"`.

The problem is that the amount of arktoshi could exceed JavaScript's `Number.MAX_SAFE_INTEGER`, so any chance of the code to accidentally start using native numbers should be nullified. Thus:

Change all `Bignum | number | string` to `Bignum | string` and adjust the fixtures.

**Comment by faustbrian** [comment]
`number | string` are only present because of tests that still use JSON fixtures so only `Bignum` should be used if you are going to work on this now.

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/core/commit/df9fd4d242f6a49eb8ac85d328c1fc6b0c800de8
