### ISSUE TITLE
Output of CLI command ark forger:log should display latest x lines

### ISSUE THREAD

**Issue by boldninja** [ArkEcosystem/core#2268]
**Is your feature request related to a problem? Please describe.**
At the moment if you setup forger and then write command ark forger:log to confirm if it was loaded ok doesn't output anything since it's waiting on the output eg:

ark@ark:~/.config/ark-core/mainnet$ ark forger:log
Waiting for /home/ark/.pm2/logs/ark-forger-out.log... ⣾

User doesn't know if it was loaded OK or if any errors.

**Describe the solution you'd like**
I'd make it similiar as with running pm2 logs ark-forger command so output some last x-lines from the file and then wait for the 'live' output if need be by message below this lines same as currently 

Waiting for /home/ark/.pm2/logs/ark-forger-out.log... ⣾ which disappears with first live instance.

Eg running pm2 logs ark-forger:

ark@ark:~/.config/ark-core/mainnet$ pm2 logs ark-forger
[TAILING] Tailing last 15 lines for [ark-forger] process (change the value with --lines option)
/home/ark/.pm2/logs/ark-forger-error.log last 15 lines:
/home/ark/.pm2/logs/ark-forger-out.log last 15 lines:
2|ark-forg | [2019-03-20 12:12:35][DEBUG]: Data Directory => /home/ark/.local/share/ark-core/mainnet
2|ark-forg | [2019-03-20 12:12:35][DEBUG]: Config Directory => /home/ark/.config/ark-core/mainnet
2|ark-forg | [2019-03-20 12:12:35][DEBUG]: Cache Directory => /home/ark/.cache/ark-core/mainnet
2|ark-forg | [2019-03-20 12:12:35][DEBUG]: Log Directory => /home/ark/.local/state/ark-core/mainnet
2|ark-forg | [2019-03-20 12:12:35][DEBUG]: Temp Directory => /tmp/ark/ark-core/mainnet
2|ark-forg | [2019-03-20 12:12:36][DEBUG]: Loaded 1 delegate: undefined (02297e602dcb3e6ee81205e9e0a7754d50cf3791b06b01fb6e9dde17059b1fb1ba)
2|ark-forg | [2019-03-20 12:12:36][INFO]: Forger Manager started with 1 forger

**Comment by dated** [comment]
FYI this feature will [not be implemented](https://github.com/lucagrulla/node-tail/issues/27) in `node-tail`.

**Comment by dated** [comment]
I'm afraid there has been some misunderstanding of the issue, as the logs output is now limited to a fixed line count, instead of going on indefinitely.
