### ISSUE TITLE
Implement snapshot system

### ISSUE THREAD

**Issue by kristjank** [ArkEcosystem/core#238]
Regular export block and transactions table.
Unfinished work is here: https://github.com/fix/ark-core/blob/master/packages/core/lib/snapshot.js
Cross-distribute snaps for faster download

Upon restore:
- Just verify blocks.id (previous.id)... 
- Verify Hashes and signatures…  -> if is in the block
- Verify the transactions (proof of the blockchain).. Signature and hash check to the block hash

**Comment by fix** [comment]
ok in this aspect we can think on incremental snapshoting:
1 - each time a block is validated it is written on db AND on snapshot
2 - every 12 hours (or instance), the snapshot is duplicated. One duplication is archived, the other is used or incremental build.

There should be some function to truncate the blockchain easily on the snapshot. or the block table it is easy (remove last heights). For transactions it is not. Maybe some kind of index based on height?

**Comment by kristjank** [comment]
conversation content moved to https://github.com/ArkEcosystem/AIPs/blob/master/AIPS/aip-19.md. will be further updated... soon

**Comment by kristjank** [comment]
➤ Kristjan Kosic commented:

<div>test</div>
