### ISSUE TITLE
improve database configuration in install.sh script

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/core#2623]
**Expected Behavior**

Allow default database options, or the ability to go back and try again until the script can proceed.

**Current Behavior**

Currently when installing a peer using the `install.sh` script, the database configuration at the end of the script does not contain default values, so entering an empty database name breaks the process. It's then impossible to go back without re-installing using the script.

**Possible Solution**

1. Fallback to default values
2. Loop until values are acceptable

**Steps to Reproduce (for bugs)**

1. Run `install.sh` script
2. When asked "Would you like to configure the database?", choose "y"
3. Press enter without providing a database name

**Context**

Deployer install.sh script in bridgechains - could do with being a little clearer as to the purpose, and make it a bit more user-friendly.

**Your Environment**

- Version used: v2.3

![image](https://user-images.githubusercontent.com/8069294/58441972-986ebd00-80de-11e9-9a3e-e2e94e2d8e19.png)

**Comment by faustbrian** [comment]
@alexbarnsley can you check the script on develop and report if you need any more changes.

**Comment by faustbrian** [comment]
ping @alexbarnsley

**Comment by alexbarnsley** [comment]
I think there needs to be an additional option when asking for name, username or password where a user can choose to go back to the default options. If they don't understand what they're being asked, it's better to provide them with a "use default" option so they don't need to worry about what they enter. if it could also catch a ctrl + c and revert to default, that would be even better. but I'm not sure if that's possible 🤷‍♂ 

this is really just to save users from having to re-install it all if they think they messed up

**Comment by supaiku0** [comment]
@vasild

**Comment by alexbarnsley** [comment]
After Vasil took a look and I re-looked at the process, ctrl + c doesn't need to be catered for during the input phase because nothing needs doing after that point. I'll properly test this when I work on updating to core v2.4 for deployer. Thanks 👌
