### ISSUE TITLE
API crashes when sorting wallet transactions

### ISSUE THREAD

**Issue by j-a-m-l** [ArkEcosystem/core#2649]
The endpoint `wallets/:address/transactions` works when sorting by some parameters:
 * `id`: https://dexplorer.ark.io:8443/api/v2/wallets/D6WrKUUhBSyrRcVcnMBhNob6GoUa1qXvns/transactions?orderBy=id:asc&limit=10&page=1
 * `timestamp`: https://dexplorer.ark.io:8443/api/v2/wallets/D6WrKUUhBSyrRcVcnMBhNob6GoUa1qXvns/transactions?orderBy=timestamp:asc&limit=10&page=1
 * `amount`: https://dexplorer.ark.io:8443/api/v2/wallets/D6WrKUUhBSyrRcVcnMBhNob6GoUa1qXvns/transactions?orderBy=amount:asc&limit=10&page=1

but fails, when sorting by others:
 * `sender`: https://dexplorer.ark.io:8443/api/v2/wallets/D6WrKUUhBSyrRcVcnMBhNob6GoUa1qXvns/transactions?orderBy=sender:asc&limit=10&page=1
 * `recipient`: https://dexplorer.ark.io:8443/api/v2/wallets/D6WrKUUhBSyrRcVcnMBhNob6GoUa1qXvns/transactions?orderBy=recipient:asc&limit=10&page=1
 * `vendorField`: https://dexplorer.ark.io:8443/api/v2/wallets/D6WrKUUhBSyrRcVcnMBhNob6GoUa1qXvns/transactions?orderBy=vendorField:asc&limit=10&page=1

The response is:
```json
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}
```

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/core/pull/2653
