### ISSUE TITLE
Automatically switch to "next" channel on Devnet via install script

### ISSUE THREAD

**Issue by boldninja** [ArkEcosystem/core#2740]
**Expected Behavior**

Automatically switch to "next" channel when installing from script (Devnet).

**Current Behavior**

When installing with install script on Devnet it doesn't switch to the "next" channel, user has  to do it manually.

**Possible Solution**

After you select which network you want to operate on if its devnet switch to "next" and republish config.

**Comment by alessiodf** [comment]
:cookieboss:

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/core/pull/2789 - Not automatically but instead asking the user as they might want to use different builds for different purposes/testing.
