### ISSUE TITLE
core-magistrate: static fees

### ISSUE THREAD

**Issue by KovacZan** [ArkEcosystem/core#3399]
**Expected Behavior**
Static fees for resignation transactions could be 0, making resignation worth applying.

**Current Behavior**
Core-magistrate resignation transaction being 50 ark.
https://github.com/ArkEcosystem/core/blob/develop/packages/core-magistrate-crypto/src/enums.ts#L14
https://github.com/ArkEcosystem/core/blob/develop/packages/core-magistrate-crypto/src/enums.ts#L17

**Possible Solution**
Lowering static fee to 0 for business-resignation and bridgechain-resignation.

**Comment by air1one** [comment]
After some discussion we will implement dynamic fees for core-magistrate transactions, which will allow low-fee resignation. See #3416
