### ISSUE TITLE
Burn balance transaction

### ISSUE THREAD

**Issue by rainydio** [ArkEcosystem/core#3530]
As discussed in #3442 there is need to simply burn balance. Calculating supply is prone to errors without dedicated burn transaction. Creating new transaction type is clean solution to the problem.

**Comment by faustbrian** [comment]
This will be worked on some time after 3.0 is stable and on mainnet.

**Comment by faustbrian** [comment]
Closing this here as it isn't an issue in terms of broken functionality https://app.clickup.com/t/9u5bn5.
