### ISSUE TITLE
refactor: transactionpool default addonBytes

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/core#3539]
Right now the transactionPool plugin defines default addonBytes in its configuration here: https://github.com/ArkEcosystem/core/blob/master/packages/core-transaction-pool/src/defaults.ts#L33

As a result, chains that don't have HTLC or magistrate transactions enabled, will still have them show up in their api endpoints as they will make use of the defaults. You can see this on mainnet where it lists HTLC fees even though we don't have those enabled: https://explorer.ark.io/api/node/configuration

**Comment by faustbrian** [comment]
In 3.0 we could make it so that the `core-magistrate-*` plugins themselves contain those options instead of the pool since those are optional plugins.

**Comment by air1one** [comment]
Closing as fixed by #3560
