### ISSUE TITLE
Integrate Triggers & Actions

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/core#3556]
Triggers allow you to overwrite specific functionality of Core which would otherwise be hard to modify and require you to touch the internals. Triggers are simply names that are associated with a function that Core will call when a trigger is fired.

We will ship with a few default triggers like `validateBlock`, `validateTransaction` and `acceptPeer` that developers can overwrite to alter the behaviour of those internal methods without having to fork a package or overwrite things via JavaScript and prototype.

## Prerequisites

Before we start, we need to establish what a few recurring variables and imports in this document refer to when they are used.

```ts
import { app, Container, Services } from "@arkecosystem/core-kernel";
```

* The `app` import refers to the application instance which grants access to the container, configurations, system information and more. 
* The `Container` import refers to a namespace that contains all of the container-specific entities like binding symbols and interfaces.
* The `Services` import refers to a namespace that contains all of the core services. This generally will only be needed for type hints as Core is responsible for service creation and maintenance.

## Architecture

The Trigger service consists of two entities - the **Triggers** and **Action** class. The **Triggers** class is responsible for storing all triggers associated with their action. The **Action** class is responsible for storing all information about an action, like what function and hooks should be executed.

When you call a `Trigger` it will tell its associated `Action` to execute and return the output of it for further processing by the application. If you don't need the return value you can simple call a Trigger and ignore its return value.

## Creating A Trigger

Creating a trigger is as simple as passing in a name and a function to the `bind` method. The given function will be called when a trigger with the given name is requested.

```ts
app
    .get<Services.Triggers.TriggerService>(Container.Identifiers.TriggerService)
    .bind("validateBlock", (data) => console.log(message));
```

## Triggering An Action

Calling a trigger is just as simple as creating it, simply pass in the name of the trigger to the `call` method together with any arguments that should be passed to it.

```ts
app
    .get<Services.Triggers.TriggerService>(Container.Identifiers.TriggerService)
    .call("log", "Hello World");
```

## Hooking Into An Action

Sometimes it might be necessary to perform some tasks before or after an action is executed and also handle the case of a failure. There are 3 methods available that allow you to specify functions that should be called `before`, on `error` and `after` an action has been executed.

### The `before` hook

The `before` hook is executed before an action is executed. **This will always be executed.**

```ts
app
    .get<Services.Triggers.TriggerService>(Container.Identifiers.TriggerService)
    .bind("validateBlock", (data) => console.log(message))
    .before(() => console.log("I am running before the action!"));
```

### The `error` hook

The `error` hook is executed when an exception is caught while the action is executed. **This will only be executed if the action itself does not handle the exception.**

```ts
app
    .get<Services.Triggers.TriggerService>(Container.Identifiers.TriggerService)
    .bind("validateBlock", (data) => console.log(message))
    .error(() => console.log("I am running if the action encounters an error!"));
```

### The `after` hook

The `after` hook is executed after an action has been executed. **This will always be executed, even if any errors are encountered.**

```ts
app
    .get<Services.Triggers.TriggerService>(Container.Identifiers.TriggerService)
    .bind("validateBlock", (data) => console.log(message))
    .after(() => console.log("I am running after the action!"));
```

## Integration

The `Triggers` service already exists at https://github.com/ArkEcosystem/core/tree/develop/packages/core-kernel/src/services/triggers with tests at https://github.com/ArkEcosystem/core/tree/develop/__tests__/unit/core-kernel/services/triggers.

The integration path will be pretty straightforward once all methods that should be treated as actions have been identified. The migration to actions would basically be just to bind the existing functions we want to be treated as actions and call them through the triggers service instead of directly on objects.

This will make it possible for developers to retrieve an action through the trigger service and add their own hooks to it before core fully boots. A few initial ones that should be fairly obvious are things like `apply/revert/validateBlock`, `apply/revert/validateTransaction` and `acceptPeer` but keep in mind that some of them might rely on https://github.com/ArkEcosystem/core/issues/3628. The impact of https://github.com/ArkEcosystem/core/issues/3628 shouldn't be too big since the whole point of those actions is to abstract away the specifics of the underlying implementation so that we only have to care about that it performs a particular task.

**Comment by sebastijankuzner** [comment]
List of potential actions:

|Package|Action|Method|
|-|-|-|
|core-blockchain|~~handleIncommingBlock~~|blockchain.handleIncomingBlock|
|core-blockchain|~~processBlocks~~|blockchain.processBlocks|
|core-blockchain|processBlock|block-processor.process|
|core-blockchain|verifyBlock|block-processor.verifyBlock|
|core-database|getActiveDelegates|block-processor.getActiveDelegates|
|core-database|verifyBlockchain|block-processor.verifyBlockchain|
|core-forger|handleDelegateTracker|delegate-tracker.handle|
|core-forger|forgeNewBlock|forger-service.forgeNewBlock|
|core-forger|isForgingAllowed|forger-service.isForgingAllowed|
|core-p2p|validateAndAcceptPeer|peer-processor.validateAndAcceptPeer|
|core-state|buildDelegateRanking|dpos.buildDelegateRanking|
|core-transaction-pool|verifyTransaction|sender-state.apply.handler.verify|
|core-transaction-pool|throwIfCannotEnterPool|sender-state.apply.handler.throwIfCannotEnterPool|
|core-transaction-pool|applyTransaction|sender-state.apply.handler.apply|
|core-transaction-pool|revertTransaction|sender-state.revert.handler.revert|

**Comment by sebastijankuzner** [comment]
List of implemented actions:

|Package|Action|Method|
|-|-|-|
|core-blockchain|processBlock|block-processor.process|
|core-database|getActiveDelegates|database-service.getActiveDelegates|
|core-forger|forgeNewBlock|forger-service.forgeNewBlock|
|core-forger|isForgingAllowed|forger-service.isForgingAllowed|
|core-p2p|validateAndAcceptPeer|peer-processor.validateAndAcceptPeer|
|core-state|buildDelegateRanking|dpos.buildDelegateRanking|
|core-transaction-pool|verifyTransaction|sender-state.apply.handler.verify|
|core-transaction-pool|throwIfCannotEnterPool|sender-state.apply.handler.throwIfCannotEnterPool|
|core-transaction-pool|applyTransaction|sender-state.apply.handler.apply|
|core-transaction-pool|revertTransaction|sender-state.revert.handler.revert|

**Comment by sebastijankuzner** [comment]
Proposed changes on triggers:

- rethrow error on executed action if no error hooks are present
- throw error if action is missing
- pass arguments to before hooks
- pass error to error hooks
- pass arguments and result to after hooks
