### ISSUE TITLE
Allow to extend core-api responses

### ISSUE THREAD

**Issue by air1one** [ArkEcosystem/core#3571]
Bridgechains may want to modify api responses from existing core-api endpoints, for example removing fields that don't make sense to them.

For example recently in 2.6 we had default dynamic fees set up for all kind of transactions in the transaction pool config.
Those default fees were picked up and showed in `api/node/configuration` endpoint which does not make sense for bridgechains for magistrate related fees as they don't have magistrate transactions.

Then allowing to extend core-api responses can help bridgechains to adapt api to their own needs.

**Comment by sebastijankuzner** [comment]
If the problem are only excess fields  then we can provide ability to extend resource objects "packages/core-api/src/resources".
