### ISSUE TITLE
Remove duplication of common code for core-transactions and core-magistrate-transactions

### ISSUE THREAD

**Issue by sebastijankuzner** [ArkEcosystem/core#3572]
Core-transactions and core-magistrate-transactions test logic uses similar code for mocks and app initialization. Support and mocks logic should be presented outside packages to remove duplication. Code can be later used for testing by new transaction packages.

**Comment by faustbrian** [comment]
This can be done after all of the coverage issues are resolved. Some common mocks should be moved into `core-test-framework`.
