### ISSUE TITLE
Extract type specific search methods out of WalletRepository

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/core#3591]
Half of the WalletRepository currently is made up of `search*` methods are specific to certain types of wallets which can be seen at https://github.com/ArkEcosystem/core/blob/develop/packages/core-state/src/wallets/wallet-repository.ts#L250-L483.

These methods are quite large and not reusable for plugins and them being private combined with their size and number are a sign that they should be looked at. We can either make them public to allow plugins to use them or extract them into `SearchContext` classes that implement a contract and allows us to implement more search types in a generic way.

**Comment by air1one** [comment]
Resolved by #3911
