### ISSUE TITLE
bug: crypto package cannot handle vendorfield > 255

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/core#3697]
the crypto SDK reads `uint8` for vendorfield length, so it's capped at 256 max and causes issues when you deploy a chain that sets a larger vendorfield limit

**Expected Behavior**

should handle larger vendorfields too

**Current Behavior**

it doesn't

**Possible Solution**

change uin8 to uin16 for a larger range

**Steps to Reproduce (for bugs)**

1. set up a chain with a larger vendorfield (e.g. 1024)
2. set up the sdk to use that network
3. try to send a tx with > 256 bytes vendorfield
4. run into ser/der issues

**Context**

**Your Environment**

- latest everything

**Comment by air1one** [comment]
We just won't allow vendorField > 255 bytes, IPFS and custom transactions are here in case anyone wants to store more data :ok_hand:
