### ISSUE TITLE
Add config parameter for core-database to allow using real counts

### ISSUE THREAD

**Issue by air1one** [ArkEcosystem/core#3711]
In core-database package add a config parameter to use real counts instead of estimates (default it to not using real counts in `defaults.ts`)

**Comment by faustbrian** [comment]
This is quite risky and could easily be abused on lower-spec nodes because the estimates were implemented specifically to let the node maintainer decide based on their specs if they can handle them or not. If we allow them to be disabled via query parameters there is no point in having them at all.

**Comment by air1one** [comment]
Ok so after talking about it, the config parameter will be enough @rainydio no need for URL param, the node maintainer decides either to allow real counts for every request or estimates for every request.

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/core/commit/1e185eab27770aa76ef409ad3805074847f63554

This simply needs to be ported to 3.0 by using the `estimateTotalCount` configuration from the `core-database` package.

**Comment by rainydio** [comment]
Implemented in #3725
