### ISSUE TITLE
Failed to fetch peers (Core v3)

### ISSUE THREAD

**Issue by boldninja** [ArkEcosystem/core#3750]
Trying to fetch a list of peers inside Desktop Wallet fails, although API endpoint (api/peers) works normally. This is related to it looking for peers that have core-api or core-wallet-api registered as plugins and not returning ports. Example:

    {
      "ip": "<ye some IP>",
      "port": "4000",
      "ports": {
      },
      "version": "3.0.0-next.0",
      "height": 45441,
      "latency": 3
    },

**Comment by air1one** [comment]
To test with latest `develop` now that #3755 is merged @boldninja , I will let you close this once you validate this is :ok:

**Comment by boldninja** [comment]
resolved :yesyes:
