### ISSUE TITLE
Core v3: API response shows 0 confirmations

### ISSUE THREAD

**Issue by boldninja** [ArkEcosystem/core#3758]
`/api/wallets/<wallet address>/transactions` API endpoint shows 0 confirmations for transactions that should be confirmed, which in result makes Desktop Wallet gray out transactions (eg. showing them as "pending") so you cannot use those funds.

**Expected Behavior**

It should show proper number of confirmations.

**Current Behavior**

It shows 0 confirmations for transactions that should be confirmed.

**Steps to Reproduce (for bugs)**

make an API call to` /api/wallets/<wallet address>/transactions` and see the response of transactions it shows 0 for them.

**Comment by rainydio** [comment]
Fixed

**Comment by rainydio** [comment]
Almost forgot about other endpoints. Reopening for now.

**Comment by rainydio** [comment]
Fixed
