### ISSUE TITLE
Create browser build for `@arkecosystem/crypto`

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/core#3784]
The primary issue is the usage of native `BigInt` that cause issues in browsers like Safari. This should be polyfilled if the native `BigInt` is not available.

**Replacing the native BigInt altogether is not a solution because the performance loss on node.js is too big with some of our new transaction types from AIP11.**

https://github.com/ArkEcosystem/mobile-wallet/blob/develop/webpack.config.js#L44-L53

**Comment by RoukePouw** [comment]
This webpack config did not work for me. I was successful shimming bigint by using 

```
  new webpack.ProvidePlugin({
    BigInt: "big-integer"
  }),
```
note the use of ProvidePlugin instead of DefinePlugin 

I also solved an issue with f.promisify by shimming util_1 which was used in `dist/sleep.js`

**Comment by faustbrian** [comment]
https://github.com/ArkEcosystem/core/pull/3830
