### ISSUE TITLE
Remove container getters

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/core#3798]
When the migration from awilix to inversify started I added 2 helpers in the form of `app.log` and `app.events`. These should be removed and replaced with injection where the logger or event dispatcher is needed. This will ensure that developers use injection and don't use internal helpers.

https://github.com/ArkEcosystem/core/blob/develop/packages/core-kernel/src/application.ts#L340-L360

**Comment by rainydio** [comment]
Done
