### ISSUE TITLE
hapi-nes tests are making core-p2p test suite fail on CI (out of memory)

### ISSUE THREAD

**Issue by air1one** [ArkEcosystem/core#3897]
hapi-nes tests in `__tests__/unit/core-p2p/hapi-nes/` are making the core-p2p test suite fail on CI.

Those tests were copy-pasted from the official hapi-nes repo, they would need some review to understand why they cause "out of memory" issue on CI.

**Comment by sebastijankuzner** [comment]
Looks like error is not present anymore.
