### ISSUE TITLE
Getting logs `Socket error (peer xxxx) : Connection terminated while waiting to connect` and peer is not dropped

### ISSUE THREAD

**Issue by air1one** [ArkEcosystem/core#3903]
When we fail to connect to a peer we get a lot of logs like `Socket error (peer xxxx) : Connection terminated while waiting to connect` and we never drop the peer.

Was supposed to be fixed by #3887 but it seems like we do not catch this connection error so we don't drop the peer.

To be sure that it is fixed, set up two nodes and disconnect them, and see if there are the debug messages.

**Comment by sebastijankuzner** [comment]
@air1one did you try after this commit? [https://github.com/ArkEcosystem/core/pull/3901](https://github.com/ArkEcosystem/core/pull/3901)

**Comment by air1one** [comment]
yeah we still have these logs on latest `develop`.
