### ISSUE TITLE
Merge package options in app.json into existing configuration (v3)

### ISSUE THREAD

**Issue by sebastijankuzner** [ArkEcosystem/core#4012]
**Expected Behavior**

Options defined in app.json/app.js should override default package setting or settings defined via process environments. For overriding it should use merging method, so existing settings are preserved. 

**Current Behavior**

In some cases options defined in app.json are ignored and current setting require setting a whole nested structure defined in app.json again.

**Comment by air1one** [comment]
Resolved by #4023
