### ISSUE TITLE
Not getting all blocks broadcast quick enough on restart

### ISSUE THREAD

**Issue by air1one** [ArkEcosystem/core#4124]
From discussion in community slack channel :

> It took 6-7min for my upgraded node to start receiving every block… It would get one or 2 after catch up, then get none, catch up again, and same repeats
> It’s like the peers ignore me after being offline(restarting) for 15sec

> I think it's likely to do with how long Nes waits to attempt a reconnection (if at all), whereas SocketCluster did it fairly quickly so any transient loss was quickly restored.

Need to fix this so that we receive all blocks broadcast on restart.

**Comment by air1one** [comment]
Did not manage to reproduce on latest develop :thinking: Need to check when we release `next` version if people still have this issue.

**Comment by rainydio** [comment]
This was probably caused by iptables rate-limit.

**Comment by alessiodf** [comment]
Still experiencing this on `next.16`, in fact even worse. Most of the time it only starts receiving blocks after the forger sends a wakeup to the relay after restarting. A non-forging node doesn't wake at all. Once it starts receiving blocks it is generally ok.

**Comment by air1one** [comment]
I don't manage to reproduce :thinking: can you try again @alessiodf and tell me if you do anything special ? Thanks

**Comment by alessiodf** [comment]
It happens often for me on multiple nodes, I don’t do anything special and there are no iptables rules or anything like that.

**Comment by air1one** [comment]
Thanks, I think I found the issue, we'll see if that PR resolves it for good.

**Comment by air1one** [comment]
Finally fixed in last release (3.0.0-next.18), closing.
