### ISSUE TITLE
Inconsistence between delegates page and monitor

### ISSUE THREAD

**Issue by TravissExe** [ArkEcosystem/core#4237]
Explorer is giving inconsistent data about last forged blocks

**Expected Behavior**

Explorer delegates monitor should show the same block status as delegates page.

**Current Behavior**

Explorer delegates page tells that all latest blocks were successfully forged, but if I go to delegates monitor I see that some blocks were missed. You can see an example below with John and Kaos.

**Delegates page**
<img width="1119" alt="delegatesPage" src="https://user-images.githubusercontent.com/76706999/103245025-1f40e700-495f-11eb-9a3a-745261ebacb9.png">

**Delegates monitor** 
<img width="1238" alt="delegatesMonitor" src="https://user-images.githubusercontent.com/76706999/103245031-223bd780-495f-11eb-8b60-3ae119f02cb9.png">

**Context**

Showing inconsistent data could be confusing.

**Comment by ItsANameToo** [comment]
@TravissExe  thanks, I moved this to our internal explorer board and will close the task here as it's not core related
