### ISSUE TITLE
Explorer page searchbar not showing

### ISSUE THREAD

**Issue by TravissExe** [ArkEcosystem/core#4239]
This bug refers to transactions list in explorer.
Sometimes page search button is not working right.

**Current Behavior**

Sometimes even if you click search button, the search bar is not showing.

**Steps to Reproduce (for bugs)**

1. Open new incognito mode tab
2. Go to Explorer, then in any user page
3. Scroll down to the pagination bar
4. Go forward until left search button shows up
5. Click on the button and see that search bar doesn't show

**Comment by ItsANameToo** [comment]
@TravissExe thanks, I moved this to our internal explorer board and will close the task here as it's not core related
