### ISSUE TITLE
Change edit Nethash

### ISSUE THREAD

**Issue by mastah12322** [ArkEcosystem/core#4296]
Hi , i have reinstaled the arc on my server, my question is can i set a custom nethash ? the old ? or this is not posibil ??

**Comment by mastah12322** [comment]
no solutions for me ?

**Comment by boldninja** [comment]
Mastah12322 sorry for the late response. Can I know what you are trying to do? If you are trying to run an ARK node instance you shouldn't change nethash (be it Mainnet or Devnet one). ARK has 2 network hash:

- Mainnet: 6e84d08bd299ed97c212c886c98a57e36545c8f5d645ca7eeae63a8bd62d8988
- Devnet:  2a44f340d76ffc3df204c5f38cd355b7496c9065a1ade2ef92071436bd72e867

Network nethash is a unique identifier that gets generated with genesis block (so each network will have a different one, but you cannot mix and match things as that will result in you not being able to sync to the correct network and other peers would reject your node).
