### ISSUE TITLE
Request to 127.0.0.1:4002<p2p.internal.getCurrentRound> failed, because of 'Request failed - server disconnected'.

### ISSUE THREAD

**Issue by alessiodf** [ArkEcosystem/core#4428]
Running two nodes, both have experienced this behaviour. One runs the unified `ark-core` and the other runs the split `ark-forger` and `ark-relay` processes.

After several hours, sometimes a day or two, the following will be printed in the log:

`Request to 127.0.0.1:4002<p2p.internal.getCurrentRound> failed, because of 'Request failed - server disconnected'` and this is usually followed by `127.0.0.1 didn't respond. Trying again later.`

In the case of the unified process, it obviously prints the message in the `ark-core` log. When using the split process, it comes from `ark-forger`.

Unfortunately there is nothing in any of the logs to explain the reason why the server disconnected, and since it is 127.0.0.1 it should not happen as it is a loopback connection which is unaffected by outside network conditions.

Note the above log messages are only printed once per incident, and the connection seems to quickly recover. **However, I consider this to be an important issue because if this disconnection coincides with our slot, we will fail to forge since the forger cannot communicate with the relay.** Indeed this happened to me tonight on devnet.

**Comment by Cactus-15-49** [comment]
I'm having the same exact problem

**Comment by alessiodf** [comment]
Please see #devnet in discord for more comprehensive logs from other delegates which confirm that this is a widespread issue affecting many people. Also worth mentioning, at least in my case, the affected nodes are powerful dedicated servers (one has 8x Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz, 32 GB RAM, 16 TB SSD, the other has 8x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz, 64 GB RAM, 0.5 TB SSD) so this is not a case of underpowered nodes not being able to keep up.

**Comment by sebastijankuzner** [comment]
Solved in #4438
