### ISSUE TITLE
POST transactions returns status 500 when transaction handler is deactivated

### ISSUE THREAD

**Issue by sebastijankuzner** [ArkEcosystem/core#4467]
**Expected Behavior**

Should return response with status 200 in form bellow:

```
data: {
    accept: [],
    broadcast: [],
    excess: [],
    invalid: []
},
errors: [],
```

Transaction should be marked as invalid with errors. 

**Current Behavior**

API responds with status 500 - (Internal Server Error). 

**Steps to Reproduce (for bugs)**

Send valid Entity transaction to api/transactions when api36 is disabled.

**Comment by rainydio** [comment]
Fixed in #4473
