### ISSUE TITLE
Throttling outgoing requests

### ISSUE THREAD

**Issue by Bomjman** [ArkEcosystem/core#4469]
Hello,
I was tried to connect my two peers on the testnet (I use Deployer-v2 for deploy) and for some reason I got the prompt from pm2 logs:
```
DEBUG: Throttling outgoing requests to 93.104.211.156/p2p.peer.getStatus to avoid triggering their rate limit
INFO : Checking 0 peers
```
I think my peers can't connect, so what reason?

OS: ubuntu 20.04

**Comment by sebastijankuzner** [comment]
Seeing this kind of message is normal, especially when there is low number of peers in the network. The message indicates that call to 93.104.211.156/p2p.peer.getStatus was delayed/throttled to prevent exceeding rate limiter on node with IP 93.104.211.156. 

You can take a look into [ENV variables](https://ark.dev/docs/core/getting-started/environment-variables) with `CORE_P2P_*` prefix, which can be used to set custom values.
