### ISSUE TITLE
Updating core while it is running causes either SIGSEGV, module not found error, or 100% CPU

### ISSUE THREAD

**Issue by alessiodf** [ArkEcosystem/core#4601]
If you update Core while it is currently running (as do most people), one of three things seem to occur:

1. bcrypto.node not found, which crashes the process:

```
1|ark-rela | Error: Cannot find module 'bcrypto.node'
1|ark-rela |     at moduleError (/home/ark/.config/yarn/global/node_modules/bcrypto/node_modules/loady/lib/loady.js:154:15)
1|ark-rela |     at resolve (/home/ark/.config/yarn/global/node_modules/bcrypto/node_modules/loady/lib/loady.js:89:9)
1|ark-rela |     at load (/home/ark/.config/yarn/global/node_modules/bcrypto/node_modules/loady/lib/loady.js:99:16)
1|ark-rela |     at Object.<anonymous> (/home/ark/.config/yarn/global/node_modules/bcrypto/lib/native/binding.js:11:33)
1|ark-rela |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
1|ark-rela |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
1|ark-rela |     at Module.load (internal/modules/cjs/loader.js:950:32)
1|ark-rela |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
1|ark-rela |     at Module.require (internal/modules/cjs/loader.js:974:19)
1|ark-rela |     at Module.Hook._require.Module.require (/home/ark/.config/yarn/global/node_modules/require-in-the-middle/index.js:80:39) {
1|ark-rela |   code: 'MODULE_NOT_FOUND'
1|ark-rela | }
```

2. SIGSEGV forcing the running process to quit:

```
PM2          | App [ark-relay:1] exited with code [0] via signal [SIGSEGV]
PM2          | App [ark-relay:1] starting in -fork mode-
PM2          | App [ark-relay:1] online
```

3. Process eats 100% CPU usage until manually restarted:

If a crypto operation occurs, and neither 1 or 2 are triggered, the Core process will get stuck with 100% CPU usage until manually restarted. This even prevents `pm2 restart` from gracefully restarting since it does not respond to either `SIGINT` or `SIGTERM`, so after a 30 second delay, pm2 resorts to `SIGKILL`.
 
All of these, I presume, are caused by the fact the bcrypto library is deleted/rebuilt as part of the update process so the already running process can't find or use it anymore. But this forces the current running instance of Core to crash, which is not desirable behaviour, especially since this can lead to a race condition where a half-updated Core gets auto-restarted by pm2 if the old process dies (triggering a respawn) before the update is fully complete. Core should be able to handle updates gracefully without crashing the currently running process until the user is ready to restart at the end.

**Comment by ajsVoren** [comment]
Can confirm, it was case number 3 for me:
`Process with pid 1316225 still alive after 30000ms, sending it SIGKILL now...`

**Comment by alessiodf** [comment]
The issue is caused by the rebuild of `better-sqlite3` during the reinstall/update process, not `bcrypto` as I originally thought.

**Comment by sebastijankuzner** [comment]
I just want to mention that the next update will probably still fail if you try to update core, because there is still old code executing update. You can prevent fails if you run: 

`rm -f "`yarn global dir`"/node_modules/better-sqlite3/build/Release/better_sqlite3.node`

before `ark update`.

Further updates after the next release (running update from 3.1.2 or 3.2.0) will use the latest code, so this line will no longer be needed.

**Comment by alessiodf** [comment]
> I just want to mention that the next update will probably still fail if you try to update core, because there is still old code executing update. You can prevent fails if you run:
> 
> **rm -f "`yarn global dir`"/node_modules/better-sqlite3/build/Release/better_sqlite3.node**
> 
> before `ark update`.
> 
> Further updates after the next release (running update from 3.1.2 or 3.2.0) will use the latest code, so this line will no longer be needed.

Almost!

The line should be
```
rm -f `yarn global dir`/node_modules/better-sqlite3/build/Release/better_sqlite3.node
```

(Backticks rather than quotes)
