### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by demicantrell** [ArkEcosystem/core#4804]
Hello.

I'm developing local core node and periodically facing with error:

`{'statusCode': 429, 'error': 'Too Many Requests', 'message': 'Too Many Requests'}`

How can I increase or disable requests limit?

**Comment by sebastijankuzner** [comment]
You can disable RateLimiter by setting environment variable (.env file) to `CORE_API_RATE_LIMIT_DISABLED=true`. Additional RateLimit setting can be applied. Please take a look into following [code section](https://github.com/ArkEcosystem/core/blob/2e6e401379e9f52922122934616476da8e5b4032/packages/core-api/src/defaults.ts#L54-L62).

Documentation is available [here](https://ark.dev/docs/core/installation/configuration#environment-configuration), with full ENV variables [list](https://ark.dev/docs/core/installation/variables).

**Comment by demicantrell** [comment]
> You can disable RateLimiter by setting environment variable (.env file) to `CORE_API_RATE_LIMIT_DISABLED=true`. Additional RateLimit setting can be applied. Please take a look into following [code section](https://github.com/ArkEcosystem/core/blob/2e6e401379e9f52922122934616476da8e5b4032/packages/core-api/src/defaults.ts#L54-L62).
> 
> Documentation is available [here](https://ark.dev/docs/core/installation/configuration#environment-configuration), with full ENV variables [list](https://ark.dev/docs/core/installation/variables).

Hi. Thanks for your hint. In the end, it turned out so that `mainnet.env` file editing did not bring the proper result. Therefore, I just changed the following lines in the `defaults.js`

```
points: process.env.CORE_API_RATE_LIMIT_USER_LIMIT || 1000000,
duration: process.env.CORE_API_RATE_LIMIT_USER_EXPIRES || 0,
```

So now everything works like a charm.
