### ISSUE TITLE
Testing guide

### ISSUE THREAD

**Issue by j-a-m-l** [ArkEcosystem/core#600]
Maybe, publishing a guide / documentation, about how to use the current tools to test would be useful. But before that, some principles or techniques should emerge from the current usage.

 - [ ] Write a guide about how to use those tools

The URL of the guide is https://arkdocs.readme.io/docs/testing

**Comment by faustbrian** [comment]
@j-a-m-l any progress on this?

**Comment by j-a-m-l** [comment]
I'll dedicate some time this week to it

**Comment by j-a-m-l** [comment]
This issue has been split: https://github.com/ArkEcosystem/core/issues/738

**Comment by kristjank** [comment]
Can we close this?
