### ISSUE TITLE
NTP is not enabled by default on Ubuntu 18.04

### ISSUE THREAD

**Issue by vmunich** [ArkEcosystem/core#644]
After installing ark-commander and going over the setup process, the node is running fine and syncing, but NTP isn't enabled:

    ===============================================================

    Core: 4fb871ea    NodeJS: 9.11.2    PG: 10.4    Redis: 4.0.10

    ===============================================================

    Relay: On    Forger: Off    NTP: Off    PG: On    Redis: On

    ===============================================================

**Server:**
 - OS: Ubuntu 18.04
 - CPU: 2 vCore
 - RAM: 4GB

**Comment by faustbrian** [comment]
@vmunich could you try https://github.com/ArkEcosystem/core-commander/commit/d08220f39f445cc66504dfb6f02cbc19e33dc9a3 which disables the default service of Ubuntu in favour of what we install.
