### ISSUE TITLE
Delegates API returns internal error

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/core#665]
**Describe the bug**
Delegates API returns internal error

**To Reproduce**

Call Delegates endpoint

http://199.247.16.109:4003/api/v2/delegates

{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}

**Expected behavior**
return list of delegates

**Screenshots**

**Server (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04

**Additional context**

**Comment by Jarunik** [comment]
Log from the node:

1|ark-core | Debug: internal, implementation, error
1|ark-core |     TypeError: Cannot read property 'id' of undefined
1|ark-core |     at module.exports (/home/jarunik/ark-core/packages/core-api/lib/versions/2/transformers/delegate.js:32:26)
1|ark-core |     at transformResource (/home/jarunik/ark-core/packages/core-api/lib/utils/transformer.js:12:160)
1|ark-core |     at data.map.d (/home/jarunik/ark-core/packages/core-api/lib/utils/transformer.js:21:75)
1|ark-core |     at Array.map (<anonymous>)
1|ark-core |     at transformCollection (/home/jarunik/ark-core/packages/core-api/lib/utils/transformer.js:21:66)
1|ark-core |     at Object.toPagination (/home/jarunik/ark-core/packages/core-api/lib/versions/2/utils.js:73:14)
1|ark-core |     at handler (/home/jarunik/ark-core/packages/core-api/lib/versions/2/handlers/delegates.js:20:18)
1|ark-core |     at <anonymous>
1|ark-core |     at process._tickCallback (internal/process/next_tick.js:182:7)

**Comment by Jarunik** [comment]
Just checked. It also happens on ubuntu 16.04 node. 

Versions:
Core: 8cdfa62c    NodeJS: 9.11.2    PG: 10.4    Redis: 4.0.10

**Comment by faustbrian** [comment]
Resolved by https://github.com/ArkEcosystem/core/pull/670
