### ISSUE TITLE
Add senderId to transaction search API

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/core#666]
**Is your feature request related to a problem? Please describe.**

http://199.247.16.109:4003/api/v2/transactions/search

There is a recipientId in the body parameters but the senderId is missing. It would be much more convinient to have the same search parameters for both sides of a transaction.

**Describe the solution you'd like**
Add senderId as search parameter.

**Describe alternatives you've considered**

**Additional context**

**Comment by faustbrian** [comment]
You can use the `senderPublicKey` for now, the `senderId` is not a real column but computed based on the `senderPublicKey`.
