### ISSUE TITLE
node not always selecting the main chain

### ISSUE THREAD

**Issue by fix** [ArkEcosystem/core#677]
The way it selects node to rebuild is too random. which can be really complex to find consensus when there are two advanced chains like on devnet.

Solution, perform a more detailed map of the nodes it can reach.

EDIT:
This issue is created by the nothing at stake (inexpensive process to create a block on both chains)

Implementation details:
-  implement configuration to let user select the chain. This is by identifying  block (id, height) you want to follow
- implement a signalisation method added to the existing (nethash, port, version) to make simple for nodes to identify peers on the same chain. The idea is to hash all selected branches together and send the first 4 bytes of the hash to the signalisation. (nethash, branch, port, version) would become the new signalisation data. ignoring this branch (like for v1) makes the selection of the branch more cumbersome.

**Comment by faustbrian** [comment]
Could be resolved by https://github.com/ArkEcosystem/core/pull/803 for now

**Comment by fix** [comment]
true that, just the common block ids is killing performance.
I believe just checking one id is enough
