### ISSUE TITLE
Log format

### ISSUE THREAD

**Issue by zillionn** [ArkEcosystem/core#678]
**Is your feature request related to a problem? Please describe.**
What's the point of this line:
https://github.com/ArkEcosystem/core/blob/9b1333487ea1556280f25d39254874db874a91e0/packages/core-logger-winston/lib/formatter.js#L36

Why don't you just remove it, the log looks strange?

<img width="1264" alt="screen shot 2018-06-18 at 20 31 00" src="https://user-images.githubusercontent.com/3462869/41552312-10901678-7337-11e8-9ae8-bfd8eaba0950.png">

**Describe the solution you'd like**
return `[${timestamp}][${level}]: ${message}`

**Describe alternatives you've considered**

**Additional context**
<img width="1267" alt="screen shot 2018-06-18 at 20 37 27" src="https://user-images.githubusercontent.com/3462869/41552472-838c359e-7337-11e8-88f3-46b4c3731492.png">

**Comment by supaiku0** [comment]
Log output mustn't be unnecessary hard to read. It's easier to parse visually with the whitespace. Especially if you spent a lot of time looking at walls of text.

I'm not saying the current format can't be improved, but let's not make it worse.

Also your proposal is not even aligned properly.  :-1:

**Comment by alexbarnsley** [comment]
Sarcasm is the lowest form of whit. How's about instead, move the lineSpacer to defaults.js and plugins.js so it is customisable? That way everyone wins with the customisation. You're welcome.

![Bob's your uncle](http://m.quickmeme.com/img/a1/a132857bb6b0e58ebd0afa632b3eaf641a8780fb3647e49e0888dbd8b9381ed1.jpg)

**Comment by zillionn** [comment]
OK move it. I have 15+ years of experience and I have never seen a log file with 30 spaces so it can be aligned! His comment was ridiculous and offensive.

**Comment by alexbarnsley** [comment]
In what way is it offensive? He even agreed that it can be improved.

**Comment by faustbrian** [comment]
As @supaiku0 said it makes reading the output easier if everything is aligned while reading walls of text if you keep your log open and you having X experience is a useless argument from authority.

All he did was explain why he thought it is like this and disagreed with you but if disagreeing with you is offensive then I would advise you to leave the internet because oh boy are you in for a surprise.

**Comment by zillionn** [comment]
Well, 

> Also your proposal is not even aligned properly. 👎

 sounded offensive. OK maybe I overreacted, I apologize.

How about:
const lineSpacer = '\t'
