### ISSUE TITLE
Improve accuracy of sync tracker

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/core#680]
The sync tracker currently is quite inaccurate as it it is based on block timestamps and slot time, so it can jump from 8 months to 40 minutes within a few minutes.

https://github.com/ArkEcosystem/core/blob/master/packages/core-blockchain/lib/utils/tick-sync-tracker.js

It would probably be better to base it on something like network height and how many blocks are downloaded per second. Maybe something else would be even more accurate.

**Comment by zillionn** [comment]
How about something like this:
```
const netHeight = 3500000
const syncStart = new Date().getTime()

let downloadedBlocks = 0
let blockPerSecond = 0
let percent = 0
let secondsLeft = 0

...
...download blocks...
downloadedBlocks += 400
...

percent = (downloadedBlocks * 100) / netHeight
blockPerSecond = ((new Date().getTime()) - syncStart) / 1000 / downloadedBlocks
secondsLeft = blockPerSecond * (netHeight - downloadedBlocks)
...
Fast Sync [==                    ] 10% (350,000 of 3,500,000 blocks) 7 hours left
```

**Comment by faustbrian** [comment]
Looks good, that is how I imagined it 👍

Makes more sense to display the progress based on actual data rather then timestamps like it is currently.

**Comment by JeremiGendron** [comment]
on it atm

**Comment by JeremiGendron** [comment]
not sure how to get netHeight, final steps and making PR

**Comment by boldninja** [comment]
Maybe this could be useful : https://github.com/ArkEcosystem/core/blob/d1181f6666f2f096724ca3083be79253817a8612/packages/core-p2p/lib/monitor.js#L242

**Comment by JeremiGendron** [comment]
getSlotNumber(currentTime)?

**Comment by boldninja** [comment]
const { slots } = require('@arkecosystem/crypto') and then slots.getSlotNumber()

**Comment by zillionn** [comment]
Wow, a ninja coder! 😄

**Comment by JeremiGendron** [comment]
finishing this later, I have a lot to learn about the codebase

**Comment by faustbrian** [comment]
@JeremiGendron You can do it like this based on zillions code.

```js
const container = require('@arkecosystem/core-container')
const logger = container.resolvePlugin('logger')

let tracker = null

module.exports = (block) => {
  if (!tracker) {
    tracker = {
      start: new Date().getTime(),
      networkHeight: container.resolvePlugin('p2p').getMonitor().getNetworkHeight(),
      downloadedBlocks: 0,
      blockPerSecond: 0,
      percent: 0,
      secondsLeft: 0
    }
  }

  tracker.downloadedBlocks += 400
  tracker.percent = (tracker.downloadedBlocks * 100) / tracker.networkHeight
  tracker.blockPerSecond = ((new Date().getTime()) - tracker.start) / 1000 / tracker.downloadedBlocks
  tracker.secondsLeft = (tracker.networkHeight - tracker.downloadedBlocks) / tracker.blockPerSecond

  if (tracker.percent < 100) {
    const downloadedBlocks = tracker.downloadedBlocks.toLocaleString()
    const networkHeight = tracker.networkHeight.toLocaleString()

    logger.printTracker('Fast Sync', tracker.percent, 100, `(${downloadedBlocks} of ${networkHeight} blocks)`)
  } else {
    tracker = null
    logger.stopTracker('Fast Sync', 100, 100)
  }
}
```

**Comment by faustbrian** [comment]
Implemented in https://github.com/ArkEcosystem/core/pull/687 - required some more changes to other parts of the core to get the necessary data.
