### ISSUE TITLE
Integrate pretty-ms for sync tracker

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/core#688]
Integrating https://github.com/sindresorhus/pretty-ms would give people a pretty printed estimate of how long the download will take at the current speed.

Could look like `(${downloadedBlocks} of ${networkHeight} blocks) ${prettyMs(secondsLeft)}` in https://github.com/ArkEcosystem/core/blob/master/packages/core-blockchain/lib/utils/tick-sync-tracker.js#L30. **Just need to make sure that the time handed in is actually presented in milliseconds for an accurate display!**

**Comment by JeremiGendron** [comment]
@faustbrian all you
