### ISSUE TITLE
problem with crypto transactions handlers / tests

### ISSUE THREAD

**Issue by JeremiGendron** [ArkEcosystem/core#703]
**Describe the bug**
this was mainly an issue with passing a potentially incompatible "wallet" object to the verifySignatures function found in crypto/lib/models/wallet.js from crypto/lib/handlers/transactions/handler.js which gets invoked by ./multi-signature.js in this case.
The test returns this error:
`
 FAIL  __tests__/handlers/transactions/multi-signature.test.js (19.007s)
  MultiSignatureHandler
    ✓ should be instantiated (15ms)
    canApply
      ✓ should be a function (1ms)
      ✓ should be ok (11510ms)
      ✕ should not be ok (419ms)
    apply
      ✓ should be a function (2ms)
      ✓ should be ok (4ms)
    revert
      ✓ should be a function (1ms)
      ✓ should be ok (1ms)

  ● MultiSignatureHandler › canApply › should not be ok

    TypeError: Cannot read property 'map' of undefined

      166 |     }
      167 | 
    > 168 |     const keysgroup = multisignature.keysgroup.map(publicKey => {
      169 |       return publicKey.startsWith('+') ? publicKey.slice(1) : publicKey
      170 |     })
      171 |     let signatures = Object.values(transaction.signatures)
      
      at Wallet.verifySignatures (lib/models/wallet.js:168:48)
      at MultiSignatureHandler.canApply (lib/handlers/transactions/handler.js:20:27)
      at MultiSignatureHandler.canApply (lib/handlers/transactions/multi-signature.js:11:16)
      at Object.it (__tests__/handlers/transactions/multi-signature.test.js:109:22)
`
the specific invocation of verifySignatures in which this error occurs is called from handler.js only, and its format is proper at every other location.

inside handler.js:
`
if (wallet.multisignature) {
      applicable = wallet.verifySignatures(transaction, wallet.multisignature)
    }
`
(found https://github.com/ArkEcosystem/core/blob/master/packages/crypto/lib/handlers/transactions/handler.js#L19)

the suggested change in the PR that follows is
`
if (wallet.multisignature) {
      applicable = wallet.verifySignatures(transaction, transaction.asset.multisignature)
    }
`
and some changes to the test file adding comments to describe the logic for other devs, branch https://github.com/JeremiGendron/core/tree/fix/crypto/handler
**To Reproduce**
run the test for multi-signature found in crypto/, trace the invocations

**Expected behavior**
the function verifySignatures gets passed a transaction object and its asset which contains the multisignature-related fields and confirms that the transaction's signatures make it a valid multisigned tx.

**Comment by faustbrian** [comment]
The `wallet.verifySignatures(transaction, wallet.multisignature)` call is correct as you can see here in the audit. https://github.com/ArkEcosystem/core/blob/master/packages/crypto/lib/models/wallet.js#L198-L200

We want to compare the `transaction.signatures` to the `wallet.multisignatures` which the wallet has registered, there must be another issue.

If you pass in `transaction.asset.multisignature` it will compare it to `transaction.asset.multisignature`, which of course will return true since they both are equal.

**Comment by JeremiGendron** [comment]
thanks, on it

**Comment by JeremiGendron** [comment]
#705 branch updated
reverted changes, instead attacked the core of the test's issue which was that it tried cycling through the wallet's multisig keygroup which might not exist whereas the transaction asset's multisignature contains the corresponding field. 
it now compares the wallet.multisignature and the keygroup from tx asset
