### ISSUE TITLE
Comparing String and Numbers in tests

### ISSUE THREAD

**Issue by JeremiGendron** [ArkEcosystem/core#711]
**Describe the bug**
The response from anyNumber.toFixed(x) is always a string, when comparing strings and numbers with .toBe(), it provides an error in the logger

this has the implications that some potentially incompatible types of data are getting passed around to arbitrary functions, potentially have the power to corrupt a process in certain situations.

**To Reproduce**
console.log(typeof (5).toFixed(2))
notice 'string' in the output
or, run `yarn test delegate-calculator`

**Expected behavior**
.toBe() gets passed an argument that is, at the very least, the same type that it tries to evaluate; in the case of delegate-calculator a number.

There are two suggestions, since this currently, to my knowledge, is only impacting of tests calling .toBe or .toEqual ; this could cause issues with other libraries so it would be smart to outright convert returned values to a standardized type, especially when it is a number calculation function.

**Additional context** 
I think this issue was spotted beforehand in some other ark-packages tests...
I would like some feedback on the proper change for these cases to be so I can make a more general PR than just fixing some test files:

should every call of .toBe(), etc, have type conversion
should the codebase be changed to convert return values to their logical expected type

i will wip

**Comment by JeremiGendron** [comment]
opening a PR with a temporary fix in the testing files only to avoid corrupting logic

**Comment by JeremiGendron** [comment]
@faustbrian  I am dedicating some time to fixing this, I would need some input from someone who's been around.

As far as I can tell, properties which are computed as numbers are also stored as such in objects. For example, the transaction amount doesn't get converted to a string with tofixed.

The only issue is with the newer properties for delegates where there's ambiguity about whether they are only logged (string conversion ok, though expensive to execute repeatedly) or if further implementations (delegate score compared to others) will reuse these values therefore they should be kept as numbers and possibly only converted to strings for logging (I prefer using templates ``)

specific props are delegate.approval and delegate.productivity, maybe keep those as numbers and add another one called delegate.score which is supposed to be final once computed and only used for logging.

if the score idea is terrible, id be happy with fixing the values at every occurrence and modifying the tests to expect numbers or strings depending on choice and making sure that any logging interface that gets called with those values gets a type conversion if demanded.

relevant packages are core-api, core-database and core-blockchain I believe

**Comment by faustbrian** [comment]
Those delegate properties are only for the API and there is a difference how they are returned for v1 and v2 so they should only be casted at the point of returning them.
