### ISSUE TITLE
Statemachine - wakeup hangs

### ISSUE THREAD

**Issue by kristjank** [ArkEcosystem/core#721]
**Describe the bug**
After usually 24h (midnight switch) state machine stops syncing from the network (by syncing - calling download blocks method)

**To Reproduce**
Keep the node running more than 24, happens after 00h

**Expected behavior**
Should keep syncing

**Logs**
https://transfer.sh/FjKbW/2018-07-01.log

**Comment by fix** [comment]
arent the log files being rotated at midnight?
