### ISSUE TITLE
TypeError triggerered after a fork rebuild

### ISSUE THREAD

**Issue by paroxysm** [ArkEcosystem/core#723]
**Describe the bug**
This crashed my v2 relay node after devnet was rewound yesterday.

See attached logs
[ark-v2-relay.zip](https://github.com/ArkEcosystem/core/files/2157626/ark-v2-relay.zip)

**Comment by kristjank** [comment]
closing this as where updates in this direction. If you can reproduces please share logs again

**Comment by paroxysm** [comment]
Cool thanks.
