### ISSUE TITLE
no ARK_P2P_ENABLED property in configs

### ISSUE THREAD

**Issue by JeremiGendron** [ArkEcosystem/core#734]
**Is your feature request related to a problem? Please describe.**
there is no "enabled" field for the core-p2p plugin in the core configs;
similar plugins have this property, including API, GRAPHQL

**Describe the solution you'd like**
have a default value for p2p enabled in core/lib/config/*/plugins.js
if the current state is intended, please close this issue
otherwise, I will prepare a PR for inclusion of this field like so:
enabled: process.env.ARK_P2P_ENABLED || (false|true)
should this field have different values based on the network to configure?
what about testnet vs devnet vs mainnet etc.

**Describe alternatives you've considered**
erroneous solutions

**Comment by JeremiGendron** [comment]
additionally, perhaps a whitelist field should be inluded, similarly to api plugin config

**Comment by faustbrian** [comment]
The P2P is not optional, it is needed for communication between nodes.
