### ISSUE TITLE
Unify tests

### ISSUE THREAD

**Issue by j-a-m-l** [ArkEcosystem/core#738]
Currently we don't have a unified way to test all the packages: some of them are using `core-test-utils` or have received more love than others.

 - [ ] Refactor to create more custom matchers
 - [ ] Refactor to remove duplicated fixtures (`genesisBlock.json`, etc.)

**Comment by j-a-m-l** [comment]
I've updated this issue to defined several specific tasks. Suggestions are welcomed.

**Comment by faustbrian** [comment]
Any progress on this? Has already been a month.

**Comment by j-a-m-l** [comment]
I've been working on https://github.com/ArkEcosystem/core/pull/783 to fix some problems that affect almost all of the packages that require setting up a blockchain. When that it's finished, I will continue with these points.

**Comment by air1one** [comment]
I think we can close this as I did a first good refactoring across the packages, using `core-test-utils` when useful. (also refactored `core-test-utils` itself).

Also wrote a doc to explain how our tests are structured and how to add / update tests for anyone to be able to do so : see here https://github.com/ArkEcosystem/docs/pull/52 (PR being reviewed)
