### ISSUE TITLE
Fork 6 - Not enough quorum to forge next block.

### ISSUE THREAD

**Issue by n4ru** [ArkEcosystem/core#758]
**Describe the bug**
Very shortly and sporadically after launching a forger on a private network, it will stop forging with the Fork 6 error.

**To Reproduce**
Launched a fresh network, connected 4 peers, all synced up and all on v2. Forger will stop and spit out an error and output that quorum is 0.5 and then 0 immediately after. Sometimes it goes straight to 0. Minimum reach is set to 1, although the network state returned shows reach is `true` and cold start is `false` at the time this occurs.

**Expected behavior**
It should forge.

**Screenshots**
n/a

**Server (please complete the following information):**
 - OS: Ubuntu
 - Version 16.04

**Additional context**
Restarting immediately fixes the issue, but it kicks back in within a few minutes at most.

After checking `/api/peers` it seems some nodes are behind, but shouldn't quorum be 0.5 if 2/4 peers are behind instead of 0?

**Comment by kristjank** [comment]
@n4ru let me know how it goes

**Comment by kristjank** [comment]
closing this. If you can reproduce please submit new issue. thanks
