### ISSUE TITLE
Add tests to core-graphql

### ISSUE THREAD

**Issue by j-a-m-l** [ArkEcosystem/core#766]
Currently this package doesn't have any test. Ideally all the code would be covered:

- [ ] Test API
- [ ] Test queries and relationships

**Comment by luciorubeens** [comment]
I'll assign this to me.

**Comment by faustbrian** [comment]
Any progress on this? Has already been 3 weeks.

**Comment by JeremiGendron** [comment]
@faustbrian may I complete the GraphQL tests?
