### ISSUE TITLE
Better core-p2p & core-blockchain parallelization

### ISSUE THREAD

**Issue by j-a-m-l** [ArkEcosystem/core#810]
Currently, the core-p2p package spawns a worker (uses https://github.com/ArkEcosystem/core/blob/master/packages/core-p2p/lib/workers/download.js) to download the blocks of a peer, but the current implementation isn't working as expected:

 - The thread is spawn at the beginning of the Peer class ((https://github.com/ArkEcosystem/core/blob/master/packages/core-p2p/lib/peer.js), but it's never killed. So it could be reused among any Peer object. This may produce problems in test environment, since the thread would be alive when the container is teared down.

 - Since the `downloadBlocks` method is `await`ing the response of the worker (on this reusable thread), the execution in the current thread is blocked, so it's not taking advantage of using that reusable thread.

Requesting the data without spawning that thread would be more efficient and less convoluted.

If we want to take advantage of parallelization, we should change it, but that would involve changing more things across the package.

**Comment by fix** [comment]
true that, i think the reuse of the thread has been lost in the rewrite into plugins somehow.

I believe this thread spawn should be moved to https://github.com/ArkEcosystem/core/blob/master/packages/core-p2p/lib/monitor.js#L343

That should be enough i think

**Comment by j-a-m-l** [comment]
Well, the problems are that:

 1. Spawning the thread isn't useful at all if the code waits to get the request response. It could be replaced entirely to execute the async request as usual.

 2. To use threads, the package should be changed to use events, a pub/sub system, or any other architecture/technique that work well async behaviour, so while the request are performed, the main JS thread isn't blocked waiting.

**Comment by j-a-m-l** [comment]
@fix What do you think about revamping some parts of some packages (primarily `core-blockchain`) to use events or something like that?

**Comment by fix** [comment]
@j-a-m-l that is true that right now spawning is not useful now. What i had in mind is to be able to connect to multiple nodes and download different part of the blockchain concurrently, but currently the v1 api does not allow that.

We need to add the number of blocks you want do download.
Once received, push it to the some list that is ordering the downloading blocks and then pushing to the  rebuild queue

**Comment by fix** [comment]
to do that we coud use https://facebook.github.io/immutable-js/docs/#/Range

**Comment by fix** [comment]
some kind of lazy structure to be able to download increasingly blocks by chunks of 100 or so

**Comment by fix** [comment]
what do you mean events? state machine is here for that

**Comment by j-a-m-l** [comment]
Maybe [generators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator) are the structure you want. They could be a way to process those blocks when they are received.

So, related to `core-p2p` we could improve it:
 - Downloading a custom number of blocks as you pointed
 - We could have a thread pool that uses and reuses a customizable number of threads to download the blocks and broadcast the transactions

When I was talking about embracing a more "evented" architecture, I was thinking on something like splitting the blockchain responsibilities into tiny state machines that interact through events. As an example:

 - We could move part of the logic of synchronization to a new state-machine on the `core-p2p` and a new class (something like `DownloadManager`) to reduce the amount of states of the blockchain machines  (and methods) and make things easier to understand.
 - That new state machine would comunicate with the blockchain emitting events that will be captured by the blockchain. So, for instance, the blockchain would care about processing a block, but it wouldn't care about how it has been downloaded, if the download is paused, etc.

I don't know enough yet about our `core` internals and I'm not completely sure about this approach, but your feedback is welcomed.

**Comment by fix** [comment]
Generator could do but i believe immutable range would be more powerful. Up to testing i guess

core-p2p: yes

event architecture: mmm not sure it would simplify. To take your example of Download Manager: the fact it is paused is triggered by too many blocks in the queue in the blockchain. and the fact that it is restarted is because the queue has drained. Essentially the p2p layer is commanded by the blockchain.

**Comment by j-a-m-l** [comment]
OK, I'll think about other ways to do it.

About this specific issue:
 - [x] https://github.com/ArkEcosystem/core/pull/828 has been merged
 - [ ] What about using threads?

**Comment by kristjank** [comment]
Is this stil active/ consider closing?

**Comment by j-a-m-l** [comment]
This could be closed.
