### ISSUE TITLE
Wrong approval calculated

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/core#812]
**Describe the bug**
The calculations for approval are wrong and will result in `NaN` and be turned into `0` by `toFixed`.

**To Reproduce**
Log the result of this https://github.com/ArkEcosystem/core/blob/master/packages/core-api/lib/utils/delegate-calculator.js#L17.

**Expected behavior**
Expecting a human readable number with 2 decimal places that is above 0.

**Additional context**
Can be easily fixed by using BigNumber.js to prevent any overflows and miscalculations. Already tested that BigNumber.js results in valid numbers.

**Comment by fix** [comment]
interesting, i find it weird that this calculation overflows here.

**Comment by alexbarnsley** [comment]
@faustbrian this is related to #827 isn't it? worth closing and leaving the other open?

**Comment by faustbrian** [comment]
Partially, once a certain threshold is hit.
