### ISSUE TITLE
Improved stateful data organisation

### ISSUE THREAD

**Issue by fix** [ArkEcosystem/core#818]
**Is your feature request related to a problem? Please describe.**
When managing and optimising te data flying around the node, there is a lack of guarantee the data is being synced.

- The data stored in the database is guaranteed for being in synced at least at each round change
- The data stored in stateMachine is guaranteed for being in synced in real time

As a general rule, any API call for node status (last delegates/blocks/wallets/transactions) should refer to in memory state (in stateMachine) before failing back to database if needed

any other source does not hold any guarantee. Examples (not yet implemented):
- get Last Block Ids
- get Last Blocks in round

**Describe the solution you'd like**
We need to replace stateMachine.state with a more meaningful (immutable?) data storage system that can be called anywhere in the code:
`state = require('./state-machine/storage')` or so

then most of the time is would be to query it:
`state.getLastBlock()`, `state.getlastBlockIds()` etc...

the Blockchain engine would update it:
`state.setLastBlock(block)` (this would update the last 100s block list)

**Comment by fix** [comment]
using https://facebook.github.io/immutable-js/ or something similar to

**Comment by faustbrian** [comment]
@fix are you actively working on this as you self-assigned it?

**Comment by fix** [comment]
not actively working on it, but will do.
