### ISSUE TITLE
unmanaged dbtransaction forces commit of opened dbtransaction

### ISSUE THREAD

**Issue by fix** [ArkEcosystem/core#830]
**Describe the bug**
I ran across this bug syncing mainnet. commenting out this solve the issue:
https://github.com/ArkEcosystem/core/blob/e15b2e7186348e010b5fbe55c8198d725ca13c15/packages/core-p2p/lib/monitor.js#L259-L262

Issue is not happening on devnet or other testnet, i believe because the unmanaged query is fast enough, or issue on implementation for sqlite3, but did not tested on pg.

This is happening when saving blog. the history of db connection is as follow:
- start deferred dbtx
- unmanaged query `getRecentBlockIds`
- save block
- save block transactions (if any)
- committing dbtx -> error transaction already committed

**To Reproduce**
sync with mainnet, then restart node

**Server (please complete the following information):**
- OS: macOS
- db: sqlite

**Comment by fix** [comment]
linked to https://github.com/ArkEcosystem/core/issues/818 since we would not need this query if implemented

**Comment by faustbrian** [comment]
No longer using sqlite so closingg this for now.
