### ISSUE TITLE
Make calculation of reverted round stateless

### ISSUE THREAD

**Issue by fix** [ArkEcosystem/core#851]
**Is your feature request related to a problem? Please describe.**
Right now when node is reverting the round (undoing a block), the list of active delegates is loaded from the table `rounds`. What would be better is to be able to calculate back the list. This issue describe the algorithm.

**Describe the solution you'd like**
- select all blocks and transactions from the previous round (optimisation: keep a few 100 blocks in memory for faster implementation)
- revert them on a temporary wallet manager: 
  - copy all delegate wallets only
  - apply blocks and transactions only on those wallets
  - for all transactions apply a special computation updating their vote stake
- order top most voted delegates

**Comment by fix** [comment]
we need to deal with memory leaks by being sure that 'old' data is being popped out

**Comment by kristjank** [comment]
is this still active, thinking tightly related to delegates in memory math ?

**Comment by faustbrian** [comment]
It will be resolved by https://github.com/ArkEcosystem/core/pull/1184
