### ISSUE TITLE
Fork issues with common blocks

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/core#852]
**Describe the bug**
Currently if a forked node cannot find any peers with a common block, it crashes (see below image). This prevents a rollback at all, and means a rebuild is necessary. In order to fix this, I think some sort of "max attempts" is required, and once that is hit it needs to establish what block it needs to rollback to.

**To Reproduce**
Begin syncing a forging node with the chain. Once established a few rounds, stop the node and then run in test mode (`ARK_ENV=test ./bin/ark start ...`). This will forge on its own chain (it has to be a forging node). Make sure at least 51 blocks are forged, then stop the node and start forging on the chain again (without `ARK_ENV=test`).

**Expected behavior**
It establishes what block to rollback to and does so.

**Screenshots**
![image](https://user-images.githubusercontent.com/8069294/44006573-93eb27de-9e7e-11e8-8fe1-39b3ddcfee77.png)

**Server (please complete the following information):**
 - OS: MacOS
 - Version: High Sierra (10.13.3)

**Additional context**
In my case I am running a 5 forger, 2 node setup. I believe the issue to still apply here.

**Comment by fix** [comment]
mmm we are using here a recursive function to find a random peer. if for some reasons, the node is disconnected, it loops recursively until recursive call stack maximum is reached.

I have seen this a few times. I am thinking about the following fix:
- de-recursify the getRandomPeer using a while loop
- perform a maximum number of tried before raising an error ('could not find peer')
- launch a network audit (ntp/dns connection test)

**Comment by alexbarnsley** [comment]
Hmm, i may have fixed this already @fix:

https://github.com/ArkEcosystem/core/commit/963f17923248adbfa08fc7c5b553871f03a6ed84#diff-5457b1a950959ee566c3948a47b74735R224

https://github.com/ArkEcosystem/core/commit/963f17923248adbfa08fc7c5b553871f03a6ed84#diff-6c9d91045605634e8224209e0a190b82R55

excluding the audit part. It tries random peers upto 10 times, then throws an exception. Might need updating/fine-tuning so can leave this issue open if you like?
