### ISSUE TITLE
Return more useful response messages on failure

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/core#865]
**Is your feature request related to a problem? Please describe.**
Currently endpoints that have no data return a `404 Not Found` response. For example, `/api/v2/transactions/BOGUS_TX_ID` returns "Not Found". This is the same response as if an endpoint doesn't exist (e.g. `/api/v2/magic`). 

**Describe the solution you'd like**
I think these need updating to make clearer, and to prevent confusion in the future.

**Comment by faustbrian** [comment]
404 **(resource not found)** is the most appropriate status code as a URL itself just represents a resource, so if the resource doesn't exist it should 404.

What status code do you think is more appropriate then not found?

**Comment by alexbarnsley** [comment]
I agree 404 is correct. This is just regarding the message itself. E.g. 404 - "Transaction not found"
