### ISSUE TITLE
Improve error message in Forger while waiting for Sync

### ISSUE THREAD

**Issue by vRobM** [ArkEcosystem/core#874]
**Is your feature request related to a problem? Please describe.**
Improve error message in Forger while waiting for Sync.

**Describe the solution you'd like**
Currently it gives a 500 and a js dump.
500 is ok, but should do a check and report the chain is not ready gracefully and not hammer the connection attempts. Put it in an await loop for when the chain completes sync?

**Describe alternatives you've considered**
slow down connection attempts when 500 errors are seen

**Comment by faustbrian** [comment]
Already has an open PR for a few hours

**Comment by vRobM** [comment]
that's great @faustbrian can you link it to close to loop?
I just looked and it wasn't obvious as most PRs are from days ago
