### ISSUE TITLE
Request Node configuration via P2P port

### ISSUE THREAD

**Issue by wownmedia** [ArkEcosystem/core#877]
When requesting the peer list from a node it will return ( _for each of the known peers_ ) the peers IP address and P2P port. To query a node for anything we need to know it's API port; and thus we can only query a node's configuration (that will show a.o. the API port) through that same  _and unknown to us_  API port.  

Currently the only work-around is to assume the API port is configured as 4003, this would be solved if:

a.) The peer list would include both ports _{ip, port, apiPort}_ 
_or_
b.) There would be an alias for the node configuration endpoint  on the p2p port.

**Comment by alexbarnsley** [comment]
@wownmedia i proposed A to @faustbrian also but I think he may be leaning towards B - you want to confirm the plan Brian?

**Comment by j-a-m-l** [comment]
:+1: to any of the options.
