### ISSUE TITLE
Forger with 8 relays

### ISSUE THREAD

**Issue by Jarunik** [ArkEcosystem/core#886]
**Describe the bug**
Forger with 8 relays will fail with fork 6.

**To Reproduce**
1. Setup 8 relays
2. Whitelist the forger on all 8 relays
3. Put all 8 relays as hosts on the forger
4. Wait for Forging
5. Fork 6

**Expected behavior**
Forging works.

**Screenshots**
n/a

**Server (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04]

**Additional context**

```
2|ark-core-forger  | [2018-08-19 10:19:11][DEBUG]                      : Loaded jarunik (035ee26e3c3597652cca2497642ade9651569815b8ef697415cbc70e828417bd53) delegates.
2|ark-core-forger  | [2018-08-19 10:19:11][INFO]                       : ForgerManager started with 1 forgers
2|ark-core-forger  | [2018-08-19 10:22:50][INFO]                       : Next forging delegate jarunik (035ee26e3c3597652cca2497642ade9651569815b8ef697415cbc70e828417bd53) is active on this node.
2|ark-core-forger  | [2018-08-19 10:22:50][DEBUG]                      : Sending wake-up check to relay node(s) http://127.0.0.1:4002
2|ark-core-forger  | [2018-08-19 10:22:51][DEBUG]                      : Sending wake-up check to relay node(s) http://45.76.94.199:4002
2|ark-core-forger  | [2018-08-19 10:22:51][DEBUG]                      : Sending wake-up check to relay node(s) http://104.238.159.113:4002
2|ark-core-forger  | [2018-08-19 10:22:52][DEBUG]                      : Sending wake-up check to relay node(s) http://149.28.165.214:4002
2|ark-core-forger  | [2018-08-19 10:22:52][DEBUG]                      : Sending wake-up check to relay node(s) http://66.42.60.249:4002
2|ark-core-forger  | [2018-08-19 10:22:52][DEBUG]                      : Sending wake-up check to relay node(s) http://198.13.38.68:4002
2|ark-core-forger  | [2018-08-19 10:22:53][DEBUG]                      : Sending wake-up check to relay node(s) http://104.238.173.32:4002
2|ark-core-forger  | [2018-08-19 10:22:53][DEBUG]                      : Sending wake-up check to relay node(s) http://45.77.61.218:4002
2|ark-core-forger  | [2018-08-19 10:22:54][DEBUG]                      : Sending wake-up check to relay node(s) http://144.202.27.195:4002
2|ark-core-forger  | [2018-08-19 10:23:02][INFO]                       : Fork 6 - Not enough quorum to forge next block.
2|ark-core-forger  | [2018-08-19 10:23:02][DEBUG]                      : Network State: {"quorum":0,"nodeHeight":169776,"lastBlockId":"7197238195869631528","overHeightBlockHeader":null,"minimumNetworkReach":true,"coldStart":false}
```

**Comment by Jarunik** [comment]
Will have to find the treshold. Forger plus 2 relays does work.

**Comment by Jarunik** [comment]
Using 4 relays on top of the forger ... so 5 nodes in total then you have too high a chance for fork 6.

2|ark-core-forger  | [2018-08-19 10:45:09][DEBUG]                      : Loaded jarunik (035ee26e3c3597652cca2497642ade9651569815b8ef697415cbc70e828417bd53) delegates.
2|ark-core-forger  | [2018-08-19 10:45:09][INFO]                       : ForgerManager started with 1 forgers
2|ark-core-forger  | [2018-08-19 10:46:02][INFO]                       : Next forging delegate jarunik (035ee26e3c3597652cca2497642ade9651569815b8ef697415cbc70e828417bd53) is active on this node.
2|ark-core-forger  | [2018-08-19 10:46:02][DEBUG]                      : Sending wake-up check to relay node(s) http://127.0.0.1:4002
2|ark-core-forger  | [2018-08-19 10:46:02][DEBUG]                      : Sending wake-up check to relay node(s) http://45.76.94.199:4002
2|ark-core-forger  | [2018-08-19 10:46:03][DEBUG]                      : Sending wake-up check to relay node(s) http://104.238.159.113:4002
2|ark-core-forger  | [2018-08-19 10:46:04][DEBUG]                      : Sending wake-up check to relay node(s) http://149.28.165.214:4002
2|ark-core-forger  | [2018-08-19 10:46:11][DEBUG]                      : Received 0 transactions from the pool containing 0 💸
2|ark-core-forger  | [2018-08-19 10:46:11][INFO]                       : Forged new block 3718152735805447571 by delegate jarunik (035ee26e3c3597652cca2497642ade9651569815b8ef697415cbc70e828417bd53) 🔱
2|ark-core-forger  | [2018-08-19 10:46:12][INFO]                       : INTERNAL: Sending forged block 3718152735805447571 at height 169,950 with 0 transactions to http://149.28.165.214:4002 📦
2|ark-core-forger  | [2018-08-19 10:55:22][INFO]                       : Next forging delegate jarunik (035ee26e3c3597652cca2497642ade9651569815b8ef697415cbc70e828417bd53) is active on this node.
2|ark-core-forger  | [2018-08-19 10:55:22][DEBUG]                      : Sending wake-up check to relay node(s) http://127.0.0.1:4002
2|ark-core-forger  | [2018-08-19 10:55:22][DEBUG]                      : Sending wake-up check to relay node(s) http://45.76.94.199:4002
2|ark-core-forger  | [2018-08-19 10:55:23][DEBUG]                      : Sending wake-up check to relay node(s) http://104.238.159.113:4002
2|ark-core-forger  | [2018-08-19 10:55:24][DEBUG]                      : Sending wake-up check to relay node(s) http://149.28.165.214:4002
2|ark-core-forger  | [2018-08-19 10:55:32][INFO]                       : Fork 6 - Not enough quorum to forge next block.
2|ark-core-forger  | [2018-08-19 10:55:32][DEBUG]                      : Network State: {"quorum":0,"nodeHeight":170019,"lastBlockId":"3033761965835898630","overHeightBlockHeader":null,"minimumNetworkReach":true,"coldStart":false}
2|ark-core-forger  | [2018-08-19 10:59:22][INFO]                       : Next forging delegate jarunik (035ee26e3c3597652cca2497642ade9651569815b8ef697415cbc70e828417bd53) is active on this node.
2|ark-core-forger  | [2018-08-19 10:59:22][DEBUG]                      : Sending wake-up check to relay node(s) http://127.0.0.1:4002
2|ark-core-forger  | [2018-08-19 10:59:22][DEBUG]                      : Sending wake-up check to relay node(s) http://45.76.94.199:4002
2|ark-core-forger  | [2018-08-19 10:59:22][DEBUG]                      : Sending wake-up check to relay node(s) http://104.238.159.113:4002
2|ark-core-forger  | [2018-08-19 10:59:22][DEBUG]                      : Sending wake-up check to relay node(s) http://149.28.165.214:4002
2|ark-core-forger  | [2018-08-19 10:59:31][DEBUG]                      : Received 0 transactions from the pool containing 0 💸
2|ark-core-forger  | [2018-08-19 10:59:31][INFO]                       : Forged new block 8433717167434940392 by delegate jarunik (035ee26e3c3597652cca2497642ade9651569815b8ef697415cbc70e828417bd53) 🔱
2|ark-core-forger  | [2018-08-19 10:59:31][INFO]                       : INTERNAL: Sending forged block 8433717167434940392 at height 170,049 with 0 transactions to http://104.238.159.113:4002 📦
2|ark-core-forger  | [2018-08-19 11:05:06][INFO]                       : Next forging delegate jarunik (035ee26e3c3597652cca2497642ade9651569815b8ef697415cbc70e828417bd53) is active on this node.
2|ark-core-forger  | [2018-08-19 11:05:06][DEBUG]                      : Sending wake-up check to relay node(s) http://127.0.0.1:4002
2|ark-core-forger  | [2018-08-19 11:05:07][DEBUG]                      : Sending wake-up check to relay node(s) http://45.76.94.199:4002
2|ark-core-forger  | [2018-08-19 11:05:07][DEBUG]                      : Sending wake-up check to relay node(s) http://104.238.159.113:4002
2|ark-core-forger  | [2018-08-19 11:05:08][DEBUG]                      : Sending wake-up check to relay node(s) http://149.28.165.214:4002
2|ark-core-forger  | [2018-08-19 11:05:18][INFO]                       : Fork 6 - Not enough quorum to forge next block.
2|ark-core-forger  | [2018-08-19 11:05:18][DEBUG]                      : Network State: {"quorum":0,"nodeHeight":170091,"lastBlockId":"15275975055677667056","overHeightBlockHeader":null,"minimumNetworkReach":true,"coldStart":false}
2|ark-core-forger  | [2018-08-19 11:14:19][INFO]                       : Next forging delegate jarunik (035ee26e3c3597652cca2497642ade9651569815b8ef697415cbc70e828417bd53) is active on this node.
2|ark-core-forger  | [2018-08-19 11:14:19][DEBUG]                      : Sending wake-up check to relay node(s) http://127.0.0.1:4002
2|ark-core-forger  | [2018-08-19 11:14:19][DEBUG]                      : Sending wake-up check to relay node(s) http://45.76.94.199:4002
2|ark-core-forger  | [2018-08-19 11:14:20][DEBUG]                      : Sending wake-up check to relay node(s) http://104.238.159.113:4002
2|ark-core-forger  | [2018-08-19 11:14:21][DEBUG]                      : Sending wake-up check to relay node(s) http://149.28.165.214:4002
2|ark-core-forger  | [2018-08-19 11:14:30][INFO]                       : Fork 6 - Not enough quorum to forge next block.
2|ark-core-forger  | [2018-08-19 11:14:30][DEBUG]                      : Network State: {"quorum":0,"nodeHeight":170159,"lastBlockId":"15886692911937636142","overHeightBlockHeader":null,"minimumNetworkReach":true,"coldStart":false}

**Comment by kristjank** [comment]
keep the relays on you local lan also. you are loosing precious time outside of the scope.
