### ISSUE TITLE
Add support milestones various Versions

### ISSUE THREAD

**Issue by EvertonMelo** [ArkEcosystem/core#895]
would not it be interesting for you to formalize the ARK Core lifecycle?
it would look something like the image below: 

![283px-software_dev2 svg](https://user-images.githubusercontent.com/7637553/44371852-5f524e00-a4b7-11e8-806c-089070c87357.png)

font: [link](https://en.wikipedia.org/wiki/Software_release_life_cycle)

in this way we can make the software more stable and scalable.

**Comment by faustbrian** [comment]
We only tag releases once each plugin has proven to run without any issues on devnet from the `develop` branch after which it will get merged to `master` for mainnet use and be published on npm.

The traditional model might be something we can consider to adapt once v2 is stable.

**Comment by EvertonMelo** [comment]
@faustbrian 

I think I was not clear.
the idea is simple.
Alpha version.
beta and stable.

bitcoin core and your milestone. 

https://github.com/bitcoin/bitcoin/milestones

**Comment by alexbarnsley** [comment]
We have Alpha, Beta, Live (stable) branches. I'm not sure how milestones would be helpful, in my opinion.

Alpha: staging branch (used to deploy to an internal testnet)
Beta: develop branch (used to run devnet nodes)
Live/stable: master branch (used to run mainnet nodes - once released)
