### ISSUE TITLE
Return feedback when posting to '/api/transactions'

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/core#899]
**Is your feature request related to a problem? Please describe.**
Currently if i send transactions to a peer to be processed, it returns telling me if it was accepted, exceeded, invalid. The problem is I don't know why it could be marked as invalid. This isn't great on a UX perspective either, as there's no feedback to give to a user as to why their transaction may have failed.

**Describe the solution you'd like**
Return `meta` data (as suggested by @faustbrian) as well as `data`, which will include the feedback associated with each transaction.

**Additional context**
This was highlighted by a potential bug whereby sending a transaction from the mobile app to 1 peer is accepted, but then marked invalid when sent to a further 9 peers.

**Comment by fix** [comment]
I agree, maybe add an `error` parameter for more meaningful description.

This `error` parameter might be normalised for all REST API endpoints
