### ISSUE TITLE
Peer list stats not updated after accepted

### ISSUE THREAD

**Issue by alexbarnsley** [ArkEcosystem/core#901]
**Describe the bug**
It looks like peer lists aren't updated in terms of height once it has been accepted.

**To Reproduce**
As an example, http://45.76.94.199:4003/api/loader/status/sync is ~191954 height. The peer list (http://45.76.94.199:4003/api/peers) have are all ~182879. These height should be updated regularly.

**Expected behavior**
Heights should be updated regularly and all be similar.

**Comment by fix** [comment]
well the intended is:
- on startup, node is scanning network
- all peers are updated when they are connected to (broadcast tx/blocks or receiving tx/blocks)
- forger before creating blocks scan again the network to perform PBFT

**Comment by fix** [comment]
I just realised that this feature disappeared with some refactoring.
to implement this properly:
- add last block header here https://github.com/ArkEcosystem/core/blob/develop/packages/core-p2p/lib/peer.js#L21
- update `this.state` here https://github.com/ArkEcosystem/core/blob/develop/packages/core-p2p/lib/peer.js#L214
- same here https://github.com/ArkEcosystem/core/blob/develop/packages/core-p2p/lib/server/plugins/set-headers.js
