### ISSUE TITLE
Implement estimate queries for improved performance

### ISSUE THREAD

**Issue by faustbrian** [ArkEcosystem/core#967]
**Problem**

The problem right now is that we have no proper pagination on the blocks & transaction endpoints because the count queries of PostgreSQL have a massive performance impact on the average server we have on mainnet.

The performance hit is caused by how count queries work, which is that they need to verify that a record exists. That means if you hit the blocks API and use a count query it has to look up almost 6 million records just to count them, this is where estimates and explaining come into play.

Estimates are information that PostgreSQL will always update by itself in the background in a meta table that contains information about our database structure and data. [EXPLAIN](https://www.postgresql.org/docs/9.4/static/using-explain.html) is a query keyword provided by PostgreSQL which allows you to analyse queries, this can also be leveraged to perform multitudes faster queries to get information like a count estimate rather then using the `COUNT` keyword.

My average `COUNT` query time on a low-tier or mid-tier server was around 60-100ms for only 115.000 records. If we scale this up to mainnet it would take us several seconds to load the blocks endpoint which is not feasible.

My average `EXPLAIN` query time on the same servers was around `650µs` which would require me to run the `EXPLAIN` query over 100 times to consume the same time of a single `COUNT` query.

_Using estimates & explain will allow us to serve larger data sets in shorter time while still providing meaningful meta data like counts and a proper pagination._

**Solution**

```sql
# Function
CREATE FUNCTION count_estimate(query text) RETURNS integer AS $$
DECLARE
  rec   record;
  rows  integer;
BEGIN
  FOR rec IN EXECUTE 'EXPLAIN ' || query LOOP
    rows := substring(rec."QUERY PLAN" FROM ' rows=([[:digit:]]+)');
    EXIT WHEN rows IS NOT NULL;
  END LOOP;
  RETURN rows;
END;
$$ LANGUAGE plpgsql VOLATILE STRICT;

# Query
SELECT count_estimate ('SELECT * FROM transactions WHERE type = 1');
```

**Comment by fix** [comment]
What about estimation in the stat table

https://stackoverflow.com/a/20574069

Also for verification of the database at start-up the counts should be exact
