### ISSUE TITLE
Remove storage package

### ISSUE THREAD

**Issue by fix** [ArkEcosystem/core#974]
I think this package is overkilling as not used at all yet and would force using some patterns that are not at all adapted when the issues related to memory storage are implemented.

It would be a lot better to learn rom how it is used to extract patterns into an independent package should there be a need or this.

**Comment by alexbarnsley** [comment]
@fix I believe core-storage is a wrapper for immutable.js with the purpose of addressing your issue here: https://github.com/ArkEcosystem/core/issues/818

**Comment by fix** [comment]
we can use immutable (or maybe something else) directly. no need or a wrapper to wrap another package. Keeping it simple.
