### ISSUE TITLE
Optimise processing of blocks

### ISSUE THREAD

**Issue by fix** [ArkEcosystem/core#975]
With the recent commits, the time to process blocks have degraded significantly. With last full rebuild (ie fastRebuild = false), the round change is taking over 2 seconds on mainnet.

A few optimisation path:
- implement #850 and overall dont rely on database for blockchain validation logic
- rationalise the way block and transaction objects are created (partially covered by wip #956)

As for the dev process, add in tests a benchmark on how long blocks and tx needs to be manipulated.
Case in point: i expect a degradation in speed when #971 is implemented. We should be able to estimate the impact o these changes rather systematically.

One good test for instance would be to rebuild 100,000 blocks on mainnet (with many transactions ideally) from height 5,000,000 to 5,100,000.The way to do that would be to:
- pull a snapshot at height 5,000,000 
- store offline the next 100,000 blocks (to get rid off unpredictable network latencies in the benchmark) reusing #238
- rebuild from the storage o those 100,000 blocks and calculate the time to do so.
- put in the PR the benchmark result.

**Comment by fix** [comment]
#990 and #991 are also linked

**Comment by fix** [comment]
#956 is done

**Comment by supaiku0** [comment]
There have been a lot of improvements over the last weeks, notably #1134, #1190, #1184, #1157 and more which have positively impacted the performance of block processing. In my opinion this can be closed and marked as done for 2.0.0. @fix
