### ISSUE TITLE
[client] Axios is not injecting the API-Version header

### ISSUE THREAD

**Issue by luciorubeens** [ArkEcosystem/core#995]
**Describe the bug**
I'm trying to use the client package, but I noticed that the axios are not injecting the header into the request.

**To Reproduce**

https://runkit.com/luciorubeens/5b9a69fcb123bf00131796be

**Expected behavior**
Make a request to the API 2.0.

**Possible alternative:**

Instead of passing the `API-Version` header, use the endpoint in the baseUrl: 

- `<host>/v2/node/configuration`
- `<host>/v1/loader/status`.

**Comment by alexbarnsley** [comment]
Looks like we just need to publish. I'm having trouble publishing though, so will give it another try in the morning

**Comment by alexbarnsley** [comment]
Success! Resolved now: https://runkit.com/alexbarnsley/5b9af07f7931b40012369af9
